import { describe, expect, it } from 'vitest';
import { QueryClient } from '@tanstack/react-query';
import { controlSearch, listHref, detailHref, returnHref, options } from './control';
import { AuthService } from './auth/AuthService';
import { RequestClient } from './request';
import type { WebIdentity } from '../utils/auth/spaces';
import { canAccessPage, pageFor } from '../router/pageAccess';
const identity = { principalType: 'PLATFORM', principalId: 'platform-subject', tenantId: null, sessionId: 'device', authorizationVersion: '3', permissionCodes: ['platform:tenant:list'], authorizedStoreIds: [], dataScope: null } as unknown as WebIdentity;
describe('平台控制面URL与正式身份边界', () => {
  it('字符串关键词保留中文、特殊字符并无损返回列表', () => { const q = controlSearch('?keyword=%E7%A7%9F%E6%88%B7%2B%26&page=3&pageSize=10&sortBy=name&sortOrder=asc'); const detail = detailHref('/platform/tenants', 'subject', q); expect(returnHref(detail.slice(detail.indexOf('?')), '/platform/tenants')).toBe(listHref('/platform/tenants', q)); expect(q.keyword).toBe('租户+&'); });
  it.each(['?page=0&pageSize=101', '?page=99999999999999999999999999', '?page=2&page=3', '?sortBy=passwordHash&sortOrder=invalid', '?keyword=x&keyword=y'])('异常输入安全回归默认条件%s', raw => { const q = controlSearch(raw); expect(q.page).toBeGreaterThan(0); expect(q.pageSize).toBeLessThanOrEqual(100); expect(q.sortBy).not.toBe('passwordHash'); });
  it('租户和账号排序白名单独立', () => { expect(controlSearch('?sortBy=loginName').sortBy).toBe('createdAt'); expect(controlSearch('?sortBy=loginName', true).sortBy).toBe('loginName'); });
  it('返回入口拒绝跨空间及外部路径', () => { for (const value of ['https://example.com', '/admin/identity/users', '/platform/accounts?keyword=other']) expect(returnHref('?returnTo=' + encodeURIComponent(value), '/platform/tenants')).toBe(listHref('/platform/tenants', controlSearch(''))); });
  it('列表读取不会授予详情或写入，STAFF不能使用PLATFORM查询', () => { const auth = new AuthService(new QueryClient()); expect(options(auth, identity, 'PLATFORM', 'tenants', 'platform:tenant:list', '/platform/tenants').enabled).toBe(true); expect(options(auth, identity, 'PLATFORM', 'tenants', 'platform:tenant:detail', '/platform/tenants/id').enabled).toBe(false); expect(options(auth, { ...identity, principalType: 'STAFF' } as WebIdentity, 'PLATFORM', 'tenants', 'platform:tenant:list', '/platform/tenants').enabled).toBe(false); });
  it('Query维度包含实际平台主体、设备、授权代际并与员工空间独立', () => { const auth = new AuthService(new QueryClient()); const key = options(auth, identity, 'PLATFORM', 'tenants', 'platform:tenant:list', '/platform/tenants').queryKey; for (const changed of [{ ...identity, principalId: 'other' }, { ...identity, sessionId: 'other' }, { ...identity, authorizationVersion: '4' }]) expect(options(auth, changed, 'PLATFORM', 'tenants', 'platform:tenant:list', '/platform/tenants').queryKey).not.toEqual(key); expect(key[0]).toMatchObject({ principalType: 'PLATFORM', tenantId: null }); });
  it('直达平台详情及租户组织同样逐权限守卫', () => { expect(canAccessPage(pageFor('PLATFORM', '/platform/tenants/id'), identity)).toBe(false); expect(canAccessPage(pageFor('PLATFORM', '/platform/tenants'), identity)).toBe(true); expect(canAccessPage(pageFor('STAFF', '/admin/identity/organizations/id'), identity)).toBe(false); });
  it('传输真实保留查询参数，不把URL拼入请求path', async () => { let observed = ''; const fetcher: typeof fetch = async input => { observed = String(input); return new Response(JSON.stringify({ success: true, data: { items: [], page: 2, pageSize: 10, total: '0' }, traceId: '0123456789abcdef0123456789abcdef' }), { headers: { 'Content-Type': 'application/json' } }); }; const client = new QueryClient(), auth = new AuthService(client, new RequestClient(fetcher)); await client.fetchQuery(options(auth, identity, 'PLATFORM', 'tenants', 'platform:tenant:list', '/platform/tenants', { page: 2, pageSize: 10, keyword: '租户&' })); expect(observed).toBe('/api/platform/tenants?page=2&pageSize=10&keyword=%E7%A7%9F%E6%88%B7%26'); });
});
