import { useRef, useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { useLocation, useRouter } from '@tanstack/react-router';
import { Alert, Button, Descriptions, Form, Input, Modal, Space, Spin, Table, Typography } from 'antd';
import type { components } from '@pet/api-contracts';
import type { WebIdentity } from '../../shared/auth/spaces';
import { useSession } from '../../shared/auth/useSession';
import { hasPermission } from '../../shared/auth/permissions';
import { ErrorNotice } from '../../shared/api/ErrorNotice';
import { managementFieldErrors, managementNameRule, requiresRecheck } from '../identity/management/api';
import { useDraftGuard } from '../identity/management/useDraftGuard';
import { safePagination } from '../identity/users/queries/pagination';
import { options } from './api';
type Organization = components['schemas']['OrganizationView'];
const path = '/admin/identity/organizations';
export function OrganizationsPage({ identity }: { identity: WebIdentity }) {
  const { auth } = useSession('STAFF', false), client = useQueryClient(), router = useRouter(), location = useLocation();
  const allowed = (action: string) => hasPermission(identity, 'STAFF', 'identity:organization:' + action);
  const id = location.pathname.slice(path.length + 1), detail = Boolean(id);const raw = new URLSearchParams(location.searchStr).get('page');const page = raw && /^[1-9][0-9]{0,9}$/.test(raw) && Number(raw) <= 2147483647 ? Number(raw) : 1;
  const list = useQuery({ ...options<components['schemas']['PageResponseOrganizationView']>(auth, identity, 'STAFF', 'organizations', 'identity:organization:list', path, { page, pageSize: 20 }), enabled: !detail && allowed('list') && !auth.runtime.isBusy(identity.principalType) });
  const selected = useQuery({ ...options<Organization>(auth, identity, 'STAFF', 'organizations', 'identity:organization:detail', path + '/' + id), enabled: detail && allowed('detail') && !auth.runtime.isBusy(identity.principalType) });
  const [mode, setMode] = useState<'create' | 'edit' | 'status'>(), [closing, setClosing] = useState(false), [recheck, setRecheck] = useState(false);
  const [form] = Form.useForm<components['schemas']['CreateOrganization']>();const lock = useRef(false);const draft = useDraftGuard(() => Boolean(mode && form.isFieldsTouched()));
  const mutation = useMutation({ gcTime: 0, retry: false, mutationFn: () => auth.runtime.request<components['schemas']['MutationResult']>('STAFF', mode === 'create' ? path : path + '/' + id + (mode === 'status' ? '/status' : ''), { method: mode === 'create' ? 'POST' : 'PUT', json: mode === 'status' ? { version: selected.data!.version, status: selected.data!.status === 'ACTIVE' ? 'DISABLED' : 'ACTIVE' } satisfies components['schemas']['ChangeStatus'] : mode === 'edit' ? { version: selected.data!.version, name: form.getFieldValue('name') } satisfies components['schemas']['EditOrganization'] : form.getFieldsValue(true) }), onSuccess: async result => { form.resetFields(); setClosing(true); setMode(undefined); await client.invalidateQueries({ predicate: q => q.queryKey[1] === 'identity' }); if (!detail && allowed('detail')) await router.navigate({ href: path + '/' + result.id + '?page=' + page }); }, onError: error => { form.setFields(managementFieldErrors(error, ['code', 'name'])); setRecheck(requiresRecheck(error)); }, onSettled: () => { lock.current = false; } });
  const open = (m: typeof mode) => { form.resetFields(); mutation.reset(); setRecheck(false); if (m === 'edit') form.setFieldValue('name', selected.data?.name); setMode(m); };
  const close = async () => { if (mutation.isPending || !await draft.mayDiscard()) return; form.resetFields(); setClosing(true); setMode(undefined); };
  const submit = () => { if (lock.current || mutation.isPending || recheck) return; lock.current = true; mutation.mutate(); };
  const pagination = list.data && safePagination(list.data.total, page, 20);
  return <>{draft.contextHolder}<Typography.Title level={2}>{detail ? '内部组织详情' : '内部组织管理'}</Typography.Title><Typography.Paragraph>内部组织是本租户的平面目录，与经营门店分开。组织不授予权限或改变员工数据范围。</Typography.Paragraph>
    {!detail ? <><Space>{allowed('create') && <Button type="primary" disabled={closing || mutation.isPending} onClick={() => open('create')}>新建内部组织</Button>}<Button onClick={() => void list.refetch()}>刷新组织列表</Button></Space>{list.isError ? <ErrorNotice error={list.error} /> : <>{pagination?.kind === 'limited' && <Alert type="warning" title={pagination.reason} />}<Table<Organization> rowKey="id" loading={list.isPending || list.isFetching} dataSource={list.data?.items} scroll={{ x: 500 }} columns={[{ title: '编码', dataIndex: 'code' }, { title: '名称', dataIndex: 'name' }, { title: '状态', render: (_, o) => o.status === 'ACTIVE' ? '启用' : '停用' }, { title: '操作', render: (_, o) => allowed('detail') && <Button onClick={() => void router.navigate({ href: path + '/' + o.id + '?page=' + page })}>查看详情</Button> }]} pagination={pagination?.kind === 'safe' ? { current: page, pageSize: 20, total: pagination.total, showSizeChanger: false, onChange: p => void router.navigate({ href: path + '?page=' + p }) } : false} /></>}</> : <><Button onClick={() => void router.navigate({ href: path + '?page=' + page })}>返回组织列表</Button><Button onClick={() => void selected.refetch()}>重新读取组织</Button>{selected.isError ? <ErrorNotice error={selected.error} /> : selected.isPending ? <Spin /> : selected.data && <><Descriptions bordered column={1} items={[{ key: 'code', label: '编码', children: selected.data.code }, { key: 'name', label: '名称', children: selected.data.name }, { key: 'status', label: '状态', children: selected.data.status === 'ACTIVE' ? '启用' : '停用' }]} /><Space>{allowed('update') && <Button disabled={closing || mutation.isPending || selected.isFetching} onClick={() => open('edit')}>修改组织名称</Button>}{allowed(selected.data.status === 'ACTIVE' ? 'disable' : 'enable') && <Button danger={selected.data.status === 'ACTIVE'} disabled={closing || mutation.isPending || selected.isFetching} onClick={() => open('status')}>{selected.data.status === 'ACTIVE' ? '停用内部组织' : '启用内部组织'}</Button>}</Space></>}</>}
    <Modal title={mode === 'create' ? '新建内部组织' : mode === 'edit' ? '修改组织名称' : '确认组织状态'} open={Boolean(mode)} destroyOnHidden maskClosable={false} footer={null} onCancel={close} afterClose={() => setClosing(false)}>{mutation.isError && <ErrorNotice error={mutation.error} title={recheck ? '请关闭并重新读取后操作' : undefined} />}{mode === 'status' ? <><Alert type="warning" title="此次操作只改变本租户组织目录，不撤销员工角色或门店授权。" /><Button danger onClick={submit} loading={mutation.isPending} disabled={recheck}>确认组织状态</Button></> : <Form form={form} layout="vertical" onFinish={submit} disabled={mutation.isPending || recheck}>{mode === 'create' && <Form.Item name="code" label="组织编码" rules={[{ required: true, pattern: /^[A-Za-z0-9][A-Za-z0-9-]{0,31}$/, message: '请输入1至32位有效编码' }]}><Input /></Form.Item>}<Form.Item name="name" label="组织名称" rules={[managementNameRule]}><Input /></Form.Item><Button type="primary" htmlType="submit" loading={mutation.isPending} disabled={recheck}>保存组织</Button></Form>}<Button disabled={mutation.isPending} onClick={close}>取消</Button></Modal>
  </>;
}
