-- 由数据库管理员显式执行；只建立无登录能力角色，不创建账号、密码或正式租户。
-- 角色已存在时失败，须核查实际权限；不自动修复未知角色。
CREATE ROLE pet_migrator NOLOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE NOINHERIT;
CREATE ROLE pet_runtime NOLOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE NOINHERIT;
CREATE ROLE pet_bootstrap NOLOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE NOINHERIT;
CREATE ROLE pet_auth_owner NOLOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE NOINHERIT;
CREATE ROLE pet_bootstrap_owner NOLOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE NOINHERIT;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE, CREATE ON SCHEMA public TO pet_migrator;
GRANT pet_auth_owner, pet_bootstrap_owner TO pet_migrator WITH INHERIT FALSE, SET TRUE;
-- 数据库名来自当前连接，仅管理员预配置使用动态标识符；正式函数没有动态SQL。
DO $$ BEGIN EXECUTE format('GRANT CREATE ON DATABASE %I TO pet_migrator',current_database()); END $$;
