-- P05-04：控制面初始化与函数能力独立于租户bootstrap，不赋运行身份高权限。
CREATE ROLE pet_platform_bootstrap NOLOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE NOINHERIT;
CREATE ROLE pet_platform_auth_owner NOLOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE NOINHERIT;
CREATE ROLE pet_platform_bootstrap_owner NOLOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE NOINHERIT;
GRANT pet_platform_auth_owner,pet_platform_bootstrap_owner TO pet_migrator WITH INHERIT FALSE, SET TRUE;
