from pathlib import Path
import hashlib,json,re,subprocess,zipfile,xml.etree.ElementTree as ET
root=Path(__file__).resolve().parents[4];ev=Path(__file__).resolve().parent
reports=ev/'verify-complete-reports'
cases=[];groups={}
for group in ('surefire','failsafe'):
 totals=dict(tests=0,failures=0,errors=0,skipped=0);suites=[]
 for p in sorted((reports/f'{group}-reports').glob('TEST-*.xml')):
  x=ET.parse(p).getroot();stats={k:int(x.attrib[k]) for k in totals};suites.append(dict(name=x.attrib['name'],**stats))
  for k,v in stats.items(): totals[k]+=v
  cases += [f"{t.attrib['classname']}#{t.attrib['name']}" for t in x.findall('testcase')]
 groups[group]=dict(totals=totals,suites=suites)
baseline=json.loads((ev/'baseline-tests.json').read_text());missing=sorted(set(baseline)-set(cases))
result=dict(groups=groups,total=len(cases),baselineCases=len(baseline),missingBaselineCases=missing,addedCases=sorted(set(cases)-set(baseline)))
(ev/'test-results.json').write_text(json.dumps(result,ensure_ascii=False,indent=2))
jar=root/'apps/backend/target/pet-platform-backend-0.0.0-SNAPSHOT.jar'
test_classroot=root/'apps/backend/target/test-classes'
testclasses={str(p.relative_to(test_classroot)) for p in test_classroot.rglob('*.class')}
testres={str(p.relative_to(root/'apps/backend/src/test/resources')) for p in (root/'apps/backend/src/test/resources').rglob('*') if p.is_file()}
with zipfile.ZipFile(jar) as z:
 entries=z.namelist()
 violations=[p for p in entries if p.removeprefix('BOOT-INF/classes/') in testclasses|testres or 'com/pet/testing/' in p or 'testcontainers-' in p or '/security-migrations/' in p]
 fixture_strings=[p for p in entries if p.startswith('BOOT-INF/classes/') and not p.endswith('/') and b'safety_parent' in z.read(p)]
 formal_sql=[p for p in entries if p.startswith('BOOT-INF/classes/db/migration/') and p.endswith('.sql')]
 production_entities=[p for p in entries if p.startswith('BOOT-INF/classes/') and p.endswith('.class') and b'Ljakarta/persistence/Entity;' in z.read(p)]
artifact=dict(path=str(jar),sha256=hashlib.sha256(jar.read_bytes()).hexdigest(),violations=violations,fixtureStrings=fixture_strings,productionSql=formal_sql,productionEntityClasses=production_entities,testClassesCompared=len(testclasses),testResourcesCompared=len(testres))
(ev/'artifact-audit.json').write_text(json.dumps(artifact,ensure_ascii=False,indent=2))
protected={p:sha for p,sha in json.loads((ev/'baseline-files.json').read_text()).items() if p.startswith(('ui/','apps/admin-web/','apps/wechat-miniprogram/','packages/','.github/','infra/')) or p in ('AGENTS.md','pnpm-lock.yaml','package.json','apps/backend/pom.xml','docs/development/VERSION-MATRIX.md') or p.startswith('docs/testing/evidence/P04-01/') or p.startswith('apps/backend/src/main/resources/db/migration/')}
preservation=[p for p,sha in protected.items() if not (root/p).is_file() or hashlib.sha256((root/p).read_bytes()).hexdigest()!=sha]
files=subprocess.check_output(['git','ls-files','--modified','--others','--exclude-standard'],cwd=root,text=True).splitlines()
# evidence generated by this audit is explicitly included in the manifest
files=sorted(set(files+['docs/testing/evidence/P04-02/final-audit.json','docs/testing/evidence/P04-02/changed-files.json']))
(ev/'changed-files.json').write_text(json.dumps(files,ensure_ascii=False,indent=2))
links=[]
for name in files:
 p=root/name
 if p.suffix!='.md' or not p.is_file():continue
 for target in re.findall(r'\]\(([^)]+)\)',p.read_text()):
  if re.match(r'^[a-z]+:',target) or target.startswith('#'):continue
  target=target.split('#')[0]
  if target and not (p.parent/target).exists():links.append(dict(file=name,target=target))
diff=subprocess.run(['git','diff','--check'],cwd=root,text=True,stdout=subprocess.PIPE,stderr=subprocess.STDOUT)
observations=[json.loads(p.read_text()) for p in (reports/'p04-02-database-observations').glob('*.json')]
security_cases=[x for x in cases if 'tenantpersistence.TenantPersistenceIT#' in x]
observation_errors=[o['test'] for o in observations if o['outsideTransactionTenantGuc']!='EMPTY' or o['runtimeRole']!='security_probe_runtime']
head=subprocess.check_output(['git','rev-parse','HEAD'],cwd=root,text=True).strip()
verify=json.loads((ev/'verify-complete.json').read_text())
summary=dict(cwd=str(root),command='python3 docs/testing/evidence/P04-02/final-audit.py',testCount=len(cases),baselineCount=len(baseline),missingBaselineCases=missing,securityDatabaseTestCount=len(security_cases),databaseSnapshots=len(observations),databaseSnapshotErrors=observation_errors,artifact=artifact,preservationChecked=len(protected),preservationViolations=preservation,missingDocumentLinks=links,diffCheckExitCode=diff.returncode,diffCheckOutput=diff.stdout,gitHead=head,gitHeadUnchanged=head==(ev/'baseline-git.txt').read_text().strip().splitlines()[-1],sourceFiles=[p for p in files if not p.startswith('docs/testing/evidence/P04-02/')])
ok=verify['exitCode']==0 and len(cases)>=114 and not missing and len(security_cases)==48 and len(observations)==48 and not observation_errors and not violations and not fixture_strings and not formal_sql and not production_entities and not preservation and not links and diff.returncode==0 and summary['gitHeadUnchanged'] and all(g['totals'][k]==0 for g in groups.values() for k in ('failures','errors','skipped'))
summary['exitCode']=0 if ok else 1
(ev/'final-audit.json').write_text(json.dumps(summary,ensure_ascii=False,indent=2))
print(json.dumps({k:v for k,v in summary.items() if k not in ('sourceFiles','artifact')},ensure_ascii=False,indent=2))
raise SystemExit(summary['exitCode'])
