package com.pet.testing.authentication;
import com.pet.platform.Application;
import com.pet.platform.customeridentity.application.*;
import com.pet.platform.identity.application.*;
import com.pet.platform.identity.application.authentication.*;
import com.pet.platform.identity.application.bootstrap.*;
import com.pet.platform.identity.infrastructure.bootstrap.*;
import com.pet.platform.identity.infrastructure.session.*;
import com.pet.platform.shared.api.*;
import com.pet.platform.shared.exception.BusinessException;
import com.pet.platform.shared.security.*;
import com.pet.platform.shared.tenancy.*;
import com.pet.testing.*;
import java.net.*;import java.net.http.*;import java.util.*;import java.util.concurrent.*;import java.util.concurrent.atomic.*;
import java.sql.*;import java.nio.file.*;import java.time.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.*;import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.context.annotation.*;import org.springframework.beans.factory.config.BeanPostProcessor;
import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.test.context.*;import org.springframework.web.bind.annotation.*;
import tools.jackson.databind.*;import tools.jackson.databind.json.JsonMapper;
import static org.junit.jupiter.api.Assertions.*;
/** 外部Gateway明确使用测试替身；正式迁移、受限PG、Sa-Token及Redis/HTTP均真实，不证明真实微信认证。 */
@SpringBootTest(classes=Application.class,webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT)
@ActiveProfiles("test") @Import(CustomerAuthenticationIT.Probes.class) @TestInstance(TestInstance.Lifecycle.PER_CLASS)
class CustomerAuthenticationIT extends PostgresIntegrationSupport {
 @LocalServerPort int port;@Autowired JsonMapper json;@Autowired CustomerIdentityStore store;@Autowired CustomerSessionPort customerSessions;@Autowired AuthenticationRedis redis;
 @Autowired PasswordService passwords;@Autowired StaffSessionPort staffSessions;@Autowired PlatformSessionPort platformSessions;@Autowired PlatformAuthentication platforms;
 JdbcTemplate owner;BootstrapResult a,b;String staffPassword;final HttpClient client=HttpClient.newHttpClient();
 static final Map<String,Object> RESPONSES=new ConcurrentHashMap<>();static final AtomicInteger CALLS=new AtomicInteger();static volatile boolean sessionFailure,cleanupFailure;
 static final String APP="wx0000000000000001",OTHER="wx0000000000000002";
 @DynamicPropertySource static void wechat(DynamicPropertyRegistry r){
  r.add("pet.wechat.enabled",()->"true");r.add("PET_WECHAT_IT_SECRET",()->"OnlyTestSecretInput1234567890");
  for(String app:List.of("main","other")){r.add("pet.wechat.applications."+app+".version",()->"1");r.add("pet.wechat.applications."+app+".app-id",()->app.equals("main")?APP:OTHER);r.add("pet.wechat.applications."+app+".secret-property",()->"PET_WECHAT_IT_SECRET");r.add("pet.wechat.applications."+app+".timeout-millis",()->"1000");r.add("pet.wechat.applications."+app+".exchanges-per-minute",()->"20");
   r.add("pet.wechat.entries."+app+".enabled",()->"true");r.add("pet.wechat.entries."+app+".application",()->app);r.add("pet.wechat.entries."+app+".tenant-codes[0]",()->"cx-a");r.add("pet.wechat.entries."+app+".tenant-codes[1]",()->"cx-b");
  }
 }
 @BeforeAll void setup(){owner=new JdbcTemplate(new DriverManagerDataSource(POSTGRES.getJdbcUrl(),POSTGRES.getUsername(),POSTGRES.getPassword()));staffPassword=UUID.randomUUID()+" 技术😀";a=tenant("cx-a");b=tenant("cx-b");}
 BootstrapResult tenant(String code){try(var r=new BootstrapRequest(code,"客户认证技术租户","admin",staffPassword.toCharArray(),null,null)){return new IdentityBootstrap(new BootstrapJdbc(Map.of("PET_BOOTSTRAP_DATABASE_URL",POSTGRES.getJdbcUrl().split("\\?",2)[0],"PET_BOOTSTRAP_DATABASE_USERNAME",IdentityDatabaseSupport.BOOTSTRAP,"PET_BOOTSTRAP_DATABASE_PASSWORD",POSTGRES.getPassword())),passwords).initialize(r);}}
 @BeforeEach void reset(){owner.execute("truncate pet_customer.security_event,public.customer_wechat_binding,public.customer_subject");owner.update("update public.platform_tenant set status='ACTIVE',security_version=0 where id in (?,?)",a.tenantId(),b.tenantId());RESPONSES.clear();CALLS.set(0);sessionFailure=false;cleanupFailure=false;var keys=redis.stringRedisTemplate.keys("pet:test:*customer*");if(keys!=null && !keys.isEmpty())redis.stringRedisTemplate.delete(keys);}
 HttpResponse<String> req(String method,String path,String body,String...headers)throws Exception{var q=HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+path)).timeout(Duration.ofSeconds(20));for(int i=0;i<headers.length;i+=2)q.header(headers[i],headers[i+1]);if(body!=null)q.header("Content-Type","application/json");return client.send(q.method(method,body==null?HttpRequest.BodyPublishers.noBody():HttpRequest.BodyPublishers.ofString(body)).build(),HttpResponse.BodyHandlers.ofString());}
 JsonNode data(HttpResponse<String> r){return json.readTree(r.body()).path("data");}
 HttpResponse<String> login(String tenant,String entry,String code)throws Exception{return req("POST","/api/customer/auth/wechat/login",json.writeValueAsString(Map.of("tenantCode",tenant,"entryId",entry,"code",code)));}
 HttpResponse<String> login()throws Exception{return login("cx-a","main",UUID.randomUUID().toString());}
 String token(HttpResponse<String> r){assertEquals(200,r.statusCode(),r.body());assertFalse(r.headers().firstValue("Set-Cookie").isPresent());return data(r).path("token").path("value").asText();}
 String token()throws Exception{return token(login());}
 HttpResponse<String> me(String t)throws Exception{return req("GET","/api/customer/auth/me",null,"X-Customer-Token","Bearer "+t);}
 void error(HttpResponse<String> r,int status,String code){assertEquals(status,r.statusCode(),r.body());assertEquals(code,json.readTree(r.body()).path("error").path("code").asText());}
 UUID customer(){return owner.queryForObject("select id from public.customer_subject",UUID.class);}
 int count(String table){return owner.queryForObject("select count(*) from "+table,Integer.class);}
 void expire(String token,String field){String key="pet:test:customer:customer:token-session:"+token;String raw=redis.get(key);assertNotNull(raw);var tree=(tools.jackson.databind.node.ObjectNode)json.readTree(raw);tree.withObject("data").put(field,"2020-01-01T00:00:00.000Z");redis.update(key,json.writeValueAsString(tree));}
 @AfterEach void observe(TestInfo info)throws Exception{sessionFailure=false;cleanupFailure=false;var dir=Path.of("target/p05-05-observations");Files.createDirectories(dir);Files.writeString(dir.resolve(info.getTestMethod().orElseThrow().getName()+".json"),json.writeValueAsString(Map.of("customer",owner.queryForList("select id,tenant_id,status,security_version,version from public.customer_subject"),"bindings",owner.queryForList("select id,tenant_id,customer_id,app_id,status from public.customer_wechat_binding"),"events",owner.queryForList("select tenant_id,principal_type,customer_id,result,occurred_at,trace_id from pet_customer.security_event"))));assertTrue(TenantContextHolder.current().isEmpty());}
 @Test void firstLoginCreatesAtomicFormalIdentityAndRealSession()throws Exception{var r=login();String t=token(r);assertEquals(1,count("public.customer_subject"));assertEquals(1,count("public.customer_wechat_binding"));assertEquals("CUSTOMER",data(r).path("identity").path("principalType").asText());assertEquals(a.tenantId().toString(),data(r).path("identity").path("tenantId").asText());assertEquals("X-Customer-Token",data(r).path("token").path("headerName").asText());assertEquals(200,me(t).statusCode());assertEquals(1,count("pet_customer.security_event"));assertFalse(r.body().contains("openId"));assertFalse(r.body().contains("unionId"));assertFalse(r.body().contains("session_key"));}
 @Test void repeatLoginReusesCustomerWithIndependentDevice()throws Exception{String first=token();UUID id=customer();String second=token();assertEquals(id,customer());assertNotEquals(first,second);assertEquals(1,count("public.customer_subject"));assertEquals(200,me(first).statusCode());assertEquals(200,me(second).statusCode());}
 @Test void concurrentFirstRegistrationHasOneBindingAndNoOrphan()throws Exception{var pool=Executors.newFixedThreadPool(8);var ready=new CyclicBarrier(8);try{var jobs=new ArrayList<Future<UUID>>();for(int i=0;i<8;i++)jobs.add(pool.submit(()->{ready.await(10,TimeUnit.SECONDS);return store.register(a.tenantId(),APP,"concurrent-open").orElseThrow().customerId();}));var ids=new HashSet<UUID>();for(var j:jobs)ids.add(j.get(20,TimeUnit.SECONDS));assertEquals(1,ids.size());assertEquals(1,count("public.customer_subject"));assertEquals(1,count("public.customer_wechat_binding"));}finally{pool.shutdownNow();}}
 @Test void concurrentHttpLoginsNeverLeaveAnOrphanAndFreshCodeRecovers()throws Exception{var pool=Executors.newFixedThreadPool(2);var barrier=new CyclicBarrier(2);try{var x=pool.submit(()->{barrier.await();return login();});var y=pool.submit(()->{barrier.await();return login();});for(var r:List.of(x.get(15,TimeUnit.SECONDS),y.get(15,TimeUnit.SECONDS)))assertTrue(Set.of(200,429).contains(r.statusCode()),r.body());assertEquals(1,count("public.customer_subject"));assertEquals(1,count("public.customer_wechat_binding"));assertEquals(200,me(token()).statusCode());}finally{pool.shutdownNow();}}
 @Test void nonUniqueDatabaseFailureRollsBackAndIsNotTreatedAsExisting(){owner.execute("create function public.customer_fail_probe() returns trigger language plpgsql as $$ begin raise exception using errcode='23514',message='技术约束故障'; end $$");owner.execute("create trigger customer_fail_probe before insert on public.customer_wechat_binding for each row execute function public.customer_fail_probe()");try{assertEquals(ErrorCode.DEPENDENCY_UNAVAILABLE,assertThrows(BusinessException.class,()->store.register(a.tenantId(),APP,"x")).error().code());assertEquals(0,count("public.customer_subject"));}finally{owner.execute("drop trigger customer_fail_probe on public.customer_wechat_binding");owner.execute("drop function public.customer_fail_probe()");}}
 @Test void tenantAppAndOpenIdAreAllPartOfBindingKey()throws Exception{String x=token(login("cx-a","main","first"));String y=token(login("cx-b","main","second"));String z=token(login("cx-a","other","third"));RESPONSES.put("fourth",new WechatMiniProgramGateway.Identity(APP,"another-open",null));String w=token(login("cx-a","main","fourth"));assertEquals(4,count("public.customer_subject"));assertNotEquals(data(me(x)).path("principalId"),data(me(y)).path("principalId"));assertEquals(b.tenantId().toString(),data(me(y)).path("tenantId").asText());error(me(x+"invalid"),401,"SESSION_EXPIRED");}
 @Test void missingUnionIdDoesNotBlockAndSameUnionDoesNotMerge()throws Exception{token();RESPONSES.put("u1",new WechatMiniProgramGateway.Identity(APP,"first-union-open","same-union"));RESPONSES.put("u2",new WechatMiniProgramGateway.Identity(APP,"second-union-open","same-union"));token(login("cx-a","main","u1"));token(login("cx-a","main","u2"));assertEquals(3,count("public.customer_subject"));assertEquals(0,owner.queryForObject("select count(*) from information_schema.columns where table_name='customer_wechat_binding' and column_name in ('union_id','session_key','code','app_secret')",Integer.class));}
 @Test void invalidCodeCreatesNoCustomerOrSession()throws Exception{RESPONSES.put("invalid",ErrorCode.WECHAT_CODE_INVALID);error(login("cx-a","main","invalid"),401,"WECHAT_CODE_INVALID");assertEquals(0,count("public.customer_subject"));assertEquals(0,redis.stringRedisTemplate.keys("pet:test:customer:customer:token:*").size());}
 @Test void timeoutRequiresFreshCodeAndNeverCreatesIdentity()throws Exception{RESPONSES.put("timeout",ErrorCode.WECHAT_RESULT_UNCERTAIN);error(login("cx-a","main","timeout"),503,"WECHAT_RESULT_UNCERTAIN");assertEquals(1,CALLS.get());assertEquals(0,count("public.customer_subject"));}
 @Test void upstreamAndMissingIdentityErrorsAreRecognizable()throws Exception{RESPONSES.put("upstream",ErrorCode.WECHAT_UPSTREAM_ERROR);error(login("cx-a","main","upstream"),503,"WECHAT_UPSTREAM_ERROR");RESPONSES.put("missing",new WechatMiniProgramGateway.Identity(APP,null,null));error(login("cx-a","main","missing"),503,"WECHAT_RESPONSE_INVALID");assertEquals(0,count("public.customer_subject"));}
 @Test void wrongApplicationResultIsRejected()throws Exception{RESPONSES.put("wrong",new WechatMiniProgramGateway.Identity(OTHER,"open",null));error(login("cx-a","main","wrong"),503,"WECHAT_RESPONSE_INVALID");assertEquals(0,count("public.customer_subject"));}
 @Test void unknownEntryAndTenantNeverExchangeCode()throws Exception{error(login("cx-a","missing","x"),401,"LOGIN_FAILED");error(login("unknown","main","x"),401,"LOGIN_FAILED");assertEquals(0,CALLS.get());}
 @Test void disabledTenantNeverExchangesAndExistingSessionRevoked()throws Exception{String t=token();owner.update("update public.platform_tenant set status='DISABLED' where id=?",a.tenantId());error(login(),401,"LOGIN_FAILED");error(me(t),401,"SESSION_REVOKED");assertEquals(1,CALLS.get());}
 @Test void disabledCustomerCannotBeRecreatedThroughLogin()throws Exception{String t=token();owner.update("update public.customer_subject set status='DISABLED' where id=?",customer());error(login(),401,"LOGIN_FAILED");error(me(t),401,"SESSION_REVOKED");assertEquals(1,count("public.customer_subject"));}
 @Test void disabledBindingCannotBeBypassed()throws Exception{String t=token();owner.execute("update public.customer_wechat_binding set status='DISABLED'");error(login(),401,"LOGIN_FAILED");error(me(t),401,"SESSION_REVOKED");assertEquals(1,count("public.customer_subject"));}
 @Test void customerAndTenantVersionInvalidateOldSessions()throws Exception{String t=token();owner.execute("update public.customer_subject set security_version=security_version+1");error(me(t),401,"SESSION_REVOKED");String fresh=token();owner.update("update public.platform_tenant set security_version=security_version+1 where id=?",a.tenantId());error(me(fresh),401,"SESSION_REVOKED");}
 @Test void sessionCreationFailureKeepsIdentityAndFreshCodeCanRetry()throws Exception{sessionFailure=true;error(login(),503,"DEPENDENCY_UNAVAILABLE");assertEquals(1,count("public.customer_subject"));assertEquals(1,count("public.customer_wechat_binding"));assertTrue(redis.stringRedisTemplate.keys("pet:test:customer:customer:token:*").isEmpty());sessionFailure=false;assertEquals(200,me(token()).statusCode());assertEquals(1,count("public.customer_subject"));}
 @Test void currentIdentityComesFromDatabaseAndProviderSelfDomain()throws Exception{String t=token();var r=req("GET","/api/customer/__customer-test/principal",null,"X-Customer-Token","Bearer "+t);assertEquals(200,r.statusCode());var d=data(r);assertEquals("CUSTOMER",d.path("domain").asText());assertEquals(customer().toString(),d.path("id").asText());assertEquals("SELF",d.path("scope").asText());assertEquals(1,data(me(t)).path("permissionCodes").size());assertEquals(0,data(me(t)).path("authorizedStoreIds").size());assertFalse(data(me(t)).toString().contains("identity:user"));}
 @Test void customerAsyncIsExplicitlyRejectedBeforeQueueing()throws Exception{String t=token();error(req("GET","/api/customer/__customer-test/task",null,"X-Customer-Token","Bearer "+t),403,"PERMISSION_DENIED");}
 @Test void customerCannotAccessStaffOrPlatformAndReverseIsRejected()throws Exception{String t=token();error(req("GET","/api/admin/auth/me",null,"X-Customer-Token","Bearer "+t),401,"AUTH_DOMAIN_MISMATCH");error(req("GET","/api/platform/auth/me",null,"X-Customer-Token","Bearer "+t),401,"AUTH_DOMAIN_MISMATCH");var staff=req("POST","/api/admin/auth/token/login",json.writeValueAsString(Map.of("tenantCode","cx-a","loginName","admin","password",staffPassword)));assertEquals(200,staff.statusCode());String st=data(staff).path("token").path("value").asText();error(req("GET","/api/customer/auth/me",null,"X-Staff-Token","Bearer "+st),401,"AUTH_DOMAIN_MISMATCH");error(me(st),401,"SESSION_EXPIRED");error(req("GET","/api/admin/auth/me",null,"X-Staff-Token","Bearer "+t),401,"SESSION_EXPIRED");}
 @Test void sameUuidAcrossThreeDomainsStillIsolated()throws Exception{UUID id=a.employeeId();owner.update("insert into public.customer_subject(id,tenant_id,status) values(?,?,'ACTIVE')",id,a.tenantId());owner.update("insert into public.customer_wechat_binding(id,tenant_id,customer_id,app_id,open_id,status) values(?,?,?,?,?,'ACTIVE')",UUID.randomUUID(),a.tenantId(),id,APP,"default-open");
  owner.update("insert into pet_control.platform_account(id,login_name,display_name,password_hash,status) values(?,?,?,?, 'ACTIVE')",id,"cx-platform","三域技术管理员",passwords.hash(staffPassword.toCharArray()));for(String permission:com.pet.platform.identity.application.authentication.PlatformPermissions.DECLARED)owner.update("insert into pet_control.platform_permission(account_id,permission_code) values(?,?)",id,permission);
  try{String ct=token();var sr=req("POST","/api/admin/auth/token/login",json.writeValueAsString(Map.of("tenantCode","cx-a","loginName","admin","password",staffPassword)));String st=data(sr).path("token").path("value").asText();var pre=req("GET","/api/platform/auth/csrf",null);String pc=pre.headers().allValues("Set-Cookie").stream().filter(v->v.startsWith("pet_dev_platform_pre=")).findFirst().orElseThrow().split(";",2)[0];var pl=req("POST","/api/platform/auth/login",json.writeValueAsString(Map.of("loginName","cx-platform","password",staffPassword)),"Cookie",pc,"X-CSRF-Token",data(pre).path("csrfToken").asText(),"Origin","http://localhost");assertEquals(200,pl.statusCode());String platformCookie=pl.headers().allValues("Set-Cookie").stream().filter(v->v.startsWith("pet_dev_platform_sid=")).findFirst().orElseThrow().split(";",2)[0];assertEquals(id.toString(),data(me(ct)).path("principalId").asText());assertEquals(id.toString(),data(req("GET","/api/admin/auth/me",null,"X-Staff-Token","Bearer "+st)).path("principalId").asText());assertEquals(id.toString(),data(req("GET","/api/platform/auth/me",null,"Cookie",platformCookie)).path("principalId").asText());
   req("POST","/api/customer/auth/logout-all",null,"X-Customer-Token","Bearer "+ct);assertEquals(200,req("GET","/api/admin/auth/me",null,"X-Staff-Token","Bearer "+st).statusCode());assertEquals(id.toString(),data(req("GET","/api/platform/auth/me",null,"Cookie",platformCookie)).path("principalId").asText());
  }finally{owner.update("delete from pet_control.platform_security_event where actor_id=? or target_id=?",id,id);owner.update("delete from pet_control.platform_session_cleanup where account_id=?",id);owner.update("delete from pet_control.platform_permission where account_id=?",id);owner.update("delete from pet_control.platform_account where id=?",id);}}
 @Test void currentLogoutInvalidatesOnlyCurrentCustomerDevice()throws Exception{String a=token(),b=token();assertEquals(200,req("POST","/api/customer/auth/logout",null,"X-Customer-Token","Bearer "+a).statusCode());error(me(a),401,"SESSION_EXPIRED");assertEquals(200,me(b).statusCode());}
 @Test void allLogoutInvalidatesEveryOldCustomerDeviceAndFreshLoginWorks()throws Exception{String x=token(),y=token();var r=req("POST","/api/customer/auth/logout-all",null,"X-Customer-Token","Bearer "+x);assertEquals(200,r.statusCode());assertEquals("COMPLETE",r.headers().firstValue("X-Session-Cleanup").orElseThrow());error(me(x),401,"SESSION_EXPIRED");error(me(y),401,"SESSION_EXPIRED");assertEquals(1,owner.queryForObject("select security_version from public.customer_subject",Integer.class));assertEquals(200,me(token()).statusCode());}
 @Test void redisCleanupFailureStillRevokesByDatabaseVersion()throws Exception{String x=token();cleanupFailure=true;var r=req("POST","/api/customer/auth/logout-all",null,"X-Customer-Token","Bearer "+x);assertEquals(200,r.statusCode());assertEquals("PENDING",r.headers().firstValue("X-Session-Cleanup").orElseThrow());error(me(x),401,"SESSION_REVOKED");cleanupFailure=false;assertEquals(200,me(token()).statusCode());assertFalse(redis.stringRedisTemplate.hasKey("pet:test:customer:customer:token:"+x));}
 @Test void delayedCustomerCleanupNeverDeletesFreshGeneration()throws Exception{String old=token();UUID id=customer();cleanupFailure=true;assertEquals(200,req("POST","/api/customer/auth/logout-all",null,"X-Customer-Token","Bearer "+old).statusCode());cleanupFailure=false;String fresh=token();customerSessions.revokeBefore(a.tenantId(),id,1);assertEquals(200,me(fresh).statusCode());}
 @Test void concurrentCustomerLogoutAllIncrementsVersionOnlyOnce()throws Exception{String t=token();var pool=Executors.newFixedThreadPool(2);var barrier=new CyclicBarrier(2);try{Callable<HttpResponse<String>> action=()->{barrier.await();return req("POST","/api/customer/auth/logout-all",null,"X-Customer-Token","Bearer "+t);};var x=pool.submit(action);var y=pool.submit(action);assertEquals(List.of(200,401),java.util.stream.Stream.of(x.get(15,TimeUnit.SECONDS),y.get(15,TimeUnit.SECONDS)).map(HttpResponse::statusCode).sorted().toList());assertEquals(1,owner.queryForObject("select security_version from public.customer_subject",Integer.class));}finally{pool.shutdownNow();}}
 @Test void absoluteAndIdlePoliciesDoNotSlideOnMe()throws Exception{var r=login();String t=token(r);assertEquals(604800,data(r).path("identity").path("idleTimeoutSeconds").asInt());long remaining=redis.getTimeout("pet:test:customer:customer:token:"+t);assertTrue(remaining>2591900 && remaining<=2592000);String key="pet:test:customer:customer:last-active:"+t;String before=redis.get(key);assertEquals(200,me(t).statusCode());assertEquals(before,redis.get(key));expire(t,"expires");error(me(t),401,"SESSION_EXPIRED");}
 @Test void idleExpiryRefusesExistingToken()throws Exception{String t=token();String key="pet:test:customer:customer:last-active:"+t;String original=redis.get(key);assertNotNull(original);redis.update(key,"1000");error(me(t),401,"SESSION_EXPIRED");}
 @Test void deviceLimitUsesSharedRedisAccountLock()throws Exception{for(int i=0;i<5;i++)token();error(login(),409,"SESSION_LIMIT_REACHED");assertEquals(1,count("public.customer_subject"));}
 @Test void noHeaderCookieQueryAndMixedCredentialsNeverBecomeCustomer()throws Exception{error(req("GET","/api/customer/auth/me",null),401,"AUTH_REQUIRED");String t=token();error(req("GET","/api/customer/auth/me?token="+t,null),400,"BAD_REQUEST");error(req("GET","/api/customer/auth/me",null,"Cookie","pet_dev_staff_sid="+t),401,"AUTH_REQUIRED");error(req("GET","/api/customer/auth/me",null,"Cookie","pet_dev_customer_sid="+t),401,"AUTH_DOMAIN_MISMATCH");error(req("GET","/api/customer/auth/me",null,"X-Customer-Token","Bearer "+t,"X-Staff-Token","Bearer "+t),400,"AUTH_CREDENTIAL_AMBIGUOUS");}
 @Test void unknownIdentityFieldsAndEncodedPathsAreRejected()throws Exception{error(req("POST","/api/customer/auth/wechat/login",json.writeValueAsString(Map.of("tenantCode","cx-a","entryId","main","code","x","openId","forged"))),400,"BAD_REQUEST");assertEquals(400,req("POST","/api/customer/auth/wechat%2flogin","{}").statusCode());assertEquals(0,CALLS.get());}
 @Test void invalidInputsCannotConsumeUnlimitedGatewayCalls()throws Exception{for(int i=0;i<60;i++)assertEquals(422,req("POST","/api/customer/auth/wechat/login","{}").statusCode());var r=req("POST","/api/customer/auth/wechat/login","{}");error(r,429,"RATE_LIMITED");assertTrue(r.headers().firstValue("Retry-After").isPresent());assertEquals(0,CALLS.get());}
 @Test void exchangeRateIsDistributedAndLimitsFailureAsWellAsSuccess()throws Exception{RESPONSES.put("invalid",ErrorCode.WECHAT_CODE_INVALID);for(int i=0;i<20;i++)error(login("cx-a","main","invalid"),401,"WECHAT_CODE_INVALID");error(login("cx-a","other","invalid"),429,"RATE_LIMITED");assertEquals(20,CALLS.get());assertTrue(redis.stringRedisTemplate.keys("pet:test:auth:customer:*").stream().noneMatch(k->k.contains("invalid")));}
 @Test void actualRedisOutageFailsClosedAndRecoversExistingSession()throws Exception{String t=token();var docker=org.testcontainers.DockerClientFactory.instance().client();docker.pauseContainerCmd(RedisTestSupport.REDIS.getContainerId()).exec();try{error(me(t),503,"DEPENDENCY_UNAVAILABLE");error(login(),503,"DEPENDENCY_UNAVAILABLE");}finally{docker.unpauseContainerCmd(RedisTestSupport.REDIS.getContainerId()).exec();}assertEquals(200,me(t).statusCode());}
 @Test void actualDatabasePermissionFaultIs503AndDoesNotDeleteSession()throws Exception{String t=token();owner.execute("revoke execute on function pet_customer.current_identity(uuid,uuid) from pet_runtime");try{error(me(t),503,"DEPENDENCY_UNAVAILABLE");}finally{owner.execute("grant execute on function pet_customer.current_identity(uuid,uuid) to pet_runtime");}assertEquals(200,me(t).statusCode());}
 @Test void runtimeRlsHasNoContextNoRowsAndCannotReadOpenIdOrElevate()throws Exception{token();try(var c=DriverManager.getConnection(POSTGRES.getJdbcUrl(),IdentityDatabaseSupport.RUNTIME,POSTGRES.getPassword());var s=c.createStatement()){
  try(var q=s.executeQuery("select rolsuper,rolbypassrls from pg_roles where rolname=current_user")){q.next();assertFalse(q.getBoolean(1));assertFalse(q.getBoolean(2));}
  try(var q=s.executeQuery("select count(*) from public.customer_subject")){q.next();assertEquals(0,q.getInt(1));}
  assertThrows(SQLException.class,()->s.execute("select open_id from public.customer_wechat_binding"));assertThrows(SQLException.class,()->s.execute("set role pet_customer_auth_owner"));assertThrows(SQLException.class,()->s.execute("truncate public.customer_subject"));
  c.setAutoCommit(false);s.execute("select set_config('pet.tenant_id','"+b.tenantId()+"',true)");try(var q=s.executeQuery("select count(*) from public.customer_subject")){q.next();assertEquals(0,q.getInt(1));}c.rollback();
  c.setAutoCommit(false);s.execute("select set_config('pet.tenant_id','"+a.tenantId()+"',true)");try(var q=s.executeQuery("select count(*) from public.customer_subject")){q.next();assertEquals(1,q.getInt(1));}c.rollback();
 }}
 @Test void compositeForeignKeyRefusesCustomerFromAnotherTenant()throws Exception{token();assertThrows(org.springframework.dao.DataIntegrityViolationException.class,()->owner.update("insert into public.customer_wechat_binding(id,tenant_id,customer_id,app_id,open_id,status) values(?,?,?,?,?,'ACTIVE')",UUID.randomUUID(),b.tenantId(),customer(),APP,"cross-tenant"));}
 @Test void eventsContainKnownIdsOnlyAndNeverExternalSecrets()throws Exception{RESPONSES.put("invalid",ErrorCode.WECHAT_CODE_INVALID);login("cx-a","main","invalid");var unknown=owner.queryForMap("select tenant_id,customer_id,result,trace_id from pet_customer.security_event");assertNull(unknown.get("customer_id"));assertEquals(a.tenantId(),unknown.get("tenant_id"));token();String events=json.writeValueAsString(owner.queryForList("select * from pet_customer.security_event"));for(String secret:List.of("default-open","same-union","OnlyTestSecretInput","session_key"))assertFalse(events.contains(secret));}
 @Test void auditWriteFailureCannotReturnSuccessfulToken()throws Exception{owner.execute("revoke insert on pet_customer.security_event from pet_customer_auth_owner");try{error(login(),503,"DEPENDENCY_UNAVAILABLE");assertEquals(1,count("public.customer_subject"));assertTrue(redis.stringRedisTemplate.keys("pet:test:customer:customer:token:*").isEmpty());}finally{owner.execute("grant insert on pet_customer.security_event to pet_customer_auth_owner");}assertEquals(200,me(token()).statusCode());}
 @TestConfiguration(proxyBeanMethods=false) static class Probes {
  @Bean @Primary WechatMiniProgramGateway testWechatGateway(){return (config,code)->{CALLS.incrementAndGet();Object result=RESPONSES.get(code);if(result instanceof ErrorCode error)throw new BusinessException(error);return result instanceof WechatMiniProgramGateway.Identity i?i:new WechatMiniProgramGateway.Identity(config.appId(),"default-open",null);};}
  @Bean static BeanPostProcessor sessionFailureOnlyInTests(){return new BeanPostProcessor(){public Object postProcessAfterInitialization(Object bean,String name){if(!(bean instanceof CustomerSessionPort))return bean;return java.lang.reflect.Proxy.newProxyInstance(CustomerSessionPort.class.getClassLoader(),new Class[]{CustomerSessionPort.class},(proxy,method,args)->{if((method.getName().equals("create")&&sessionFailure)||(method.getName().equals("revokeBefore")&&cleanupFailure))throw new BusinessException(ErrorCode.DEPENDENCY_UNAVAILABLE);try{return method.invoke(bean,args);}catch(java.lang.reflect.InvocationTargetException e){throw e.getCause();}});}};}
  @Bean Probe customerProbe(CurrentPrincipalProvider provider,TenantTaskExecutor tasks){return new Probe(provider,tasks);}
 }
 @RestController static class Probe {
  private final CurrentPrincipalProvider provider;private final TenantTaskExecutor tasks;Probe(CurrentPrincipalProvider p,TenantTaskExecutor t){provider=p;tasks=t;}
  @GetMapping("/api/customer/__customer-test/principal") ApiResponse.Success<Map<String,String>> principal(){var p=provider.currentPrincipal().orElseThrow();return ApiResponse.success(Map.of("domain",p.principalType().name(),"id",p.principalId().toString(),"scope",p.grants().get(CustomerHttpAuthentication.SESSION_PERMISSION).types().iterator().next().name()));}
  @GetMapping("/api/customer/__customer-test/task") ApiResponse.Success<Void> task(){try(var s=TenantExecutionScope.forPermission(CustomerHttpAuthentication.SESSION_PERMISSION)){tasks.submit(()->null);return ApiResponse.success(null);}}
 }
}
