package com.pet.testing.authentication;

import com.pet.platform.Application;
import com.pet.platform.identity.application.*;
import com.pet.platform.identity.application.authentication.*;
import com.pet.platform.identity.application.bootstrap.*;
import com.pet.platform.identity.infrastructure.bootstrap.*;
import com.pet.platform.identity.infrastructure.session.*;
import com.pet.platform.shared.api.ErrorCode;
import com.pet.platform.shared.exception.BusinessException;
import com.pet.platform.shared.security.*;
import com.pet.platform.shared.redis.*;
import com.pet.platform.shared.tenancy.*;
import com.pet.testing.*;
import java.io.*;
import java.net.*;
import java.net.http.*;
import java.nio.file.*;
import java.sql.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.*;
import java.lang.reflect.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.config.BeanPostProcessor;
import org.springframework.boot.test.context.*;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.context.annotation.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.web.bind.annotation.*;
import jakarta.servlet.http.*;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.json.JsonMapper;
import static org.junit.jupiter.api.Assertions.*;

/** 全部身份由正式命令/密码/真实Sa-Token建立，故障与屏障只存在于测试。 */
@SpringBootTest(classes=Application.class,webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT)
@ActiveProfiles("test") @Import(PlatformAuthenticationIT.Probes.class)
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class PlatformAuthenticationIT extends PostgresIntegrationSupport {
    @LocalServerPort int port;
    @Autowired PasswordService passwords;
    @Autowired AuthenticationRedis redis;
    @Autowired PlatformSessionPort sessions;
    @Autowired JsonMapper json;
    JdbcTemplate owner;UUID id;String password,next,staffPassword,tenant;
    BootstrapResult staff;
    final HttpClient client=HttpClient.newHttpClient();
    static final Controls CONTROL=new Controls();
    record Web(String cookie,String csrf) { @Override public String toString(){return "Web[受限测试会话]";} }
    static class Gate{final CountDownLatch entered=new CountDownLatch(1),release=new CountDownLatch(1);void waitHere(){entered.countDown();try{if(!release.await(15,TimeUnit.SECONDS))throw new IllegalStateException("测试关卡超时");}catch(InterruptedException e){Thread.currentThread().interrupt();throw new IllegalStateException("测试关卡取消");}}}
    static class Controls {volatile boolean cleanupFailure,eventFailure,pauseCleanup;volatile Gate login,cleanup;void clear(){cleanupFailure=false;eventFailure=false;pauseCleanup=false;if(login!=null)login.release.countDown();if(cleanup!=null)cleanup.release.countDown();login=null;cleanup=null;}}
    @BeforeAll void owner(){owner=new JdbcTemplate(new DriverManagerDataSource(POSTGRES.getJdbcUrl(),POSTGRES.getUsername(),POSTGRES.getPassword()));}
    Map<String,String> environment(){return Map.of("PET_PLATFORM_BOOTSTRAP_DATABASE_URL",POSTGRES.getJdbcUrl().split("\\?",2)[0],"PET_PLATFORM_BOOTSTRAP_DATABASE_USERNAME",IdentityDatabaseSupport.PLATFORM_BOOTSTRAP,"PET_PLATFORM_BOOTSTRAP_DATABASE_PASSWORD",POSTGRES.getPassword());}
    int command(String name,String raw,Map<String,String> env){var out=new ByteArrayOutputStream();var err=new ByteArrayOutputStream();int code=PlatformBootstrapCommand.run(new String[]{"--admin-login",name,"--admin-name","平台技术管理员","--password-stdin"},env,new ByteArrayInputStream((raw+"\n").getBytes(java.nio.charset.StandardCharsets.UTF_8)),new PrintStream(out),new PrintStream(err));assertFalse(out.toString().contains(raw));assertFalse(err.toString().contains(raw));assertFalse(out.toString().contains("$pbkdf2"));return code;}
    @BeforeEach void initialize(){
        CONTROL.clear();owner.execute("truncate pet_control.platform_security_event,pet_control.platform_session_cleanup,pet_control.platform_bootstrap,pet_control.platform_permission,pet_control.platform_account");
        password=UUID.randomUUID()+" 平台😀 ";next=UUID.randomUUID()+" 新平台😀 ";staffPassword=UUID.randomUUID()+" 员工😀 ";
        redis.stringRedisTemplate.delete(redis.stringRedisTemplate.keys("pet:test:auth:platform:*") ); // 测试隔离命名空间，生产DAO禁用扫描。
        assertEquals(0,command(" Root ",password,environment()));id=owner.queryForObject("select id from pet_control.platform_account",UUID.class);
        tenant="p"+UUID.randomUUID().toString().replace("-","").substring(0,20);
        try(var r=new BootstrapRequest(tenant,"双域技术租户","admin",staffPassword.toCharArray(),"store","技术门店")){
            staff=new IdentityBootstrap(new BootstrapJdbc(Map.of("PET_BOOTSTRAP_DATABASE_URL",POSTGRES.getJdbcUrl().split("\\?",2)[0],"PET_BOOTSTRAP_DATABASE_USERNAME",IdentityDatabaseSupport.BOOTSTRAP,"PET_BOOTSTRAP_DATABASE_PASSWORD",POSTGRES.getPassword())),passwords).initialize(r);
        }
        redis.stringRedisTemplate.delete(List.of("pet:test:auth:staff:ip:"+SaStaffSessions.digest("127.0.0.1")));
    }
    HttpResponse<String> request(String method,String path,String body,String...headers)throws Exception{
        var b=HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+path)).timeout(java.time.Duration.ofSeconds(25));for(int i=0;i<headers.length;i+=2)b.header(headers[i],headers[i+1]);if(body!=null)b.header("Content-Type","application/json");
        return client.send(b.method(method,body==null?HttpRequest.BodyPublishers.noBody():HttpRequest.BodyPublishers.ofString(body)).build(),HttpResponse.BodyHandlers.ofString());
    }
    String body(Map<String,?> v){return json.writeValueAsString(v);}JsonNode data(HttpResponse<String> r){return json.readTree(r.body()).path("data");}
    String cookie(HttpResponse<String> r,String name){return r.headers().allValues("Set-Cookie").stream().filter(s -> s.startsWith(name+"=")).findFirst().orElseThrow().split(";",2)[0];}
    HttpResponse<String> login(String name,String pwd)throws Exception{var pre=request("GET","/api/platform/auth/csrf",null);assertEquals(200,pre.statusCode());return request("POST","/api/platform/auth/login",body(Map.of("loginName",name,"password",pwd)),"Cookie",cookie(pre,"pet_dev_platform_pre"),"X-CSRF-Token",data(pre).path("csrfToken").asText(),"Origin","http://localhost");}
    Web web(String pwd)throws Exception{var r=login("root",pwd);assertEquals(200,r.statusCode(),r.body());String sid=cookie(r,"pet_dev_platform_sid");return new Web(sid,data(request("GET","/api/platform/auth/csrf",null,"Cookie",sid)).path("csrfToken").asText());}
    Web web()throws Exception{return web(password);}
    Web staffWeb()throws Exception{var pre=request("GET","/api/admin/auth/csrf",null);var r=request("POST","/api/admin/auth/login",body(Map.of("tenantCode",tenant,"loginName","admin","password",staffPassword)),"Cookie",cookie(pre,"pet_dev_staff_pre"),"X-CSRF-Token",data(pre).path("csrfToken").asText(),"Origin","http://localhost");assertEquals(200,r.statusCode());String sid=cookie(r,"pet_dev_staff_sid");return new Web(sid,data(request("GET","/api/admin/auth/csrf",null,"Cookie",sid)).path("csrfToken").asText());}
    String staffToken(String name)throws Exception{var r=request("POST","/api/admin/auth/token/login",body(Map.of("tenantCode",tenant,"loginName",name,"password",staffPassword)));assertEquals(200,r.statusCode());return data(r).path("token").path("value").asText();}
    HttpResponse<String> me(Web w)throws Exception{return request("GET","/api/platform/auth/me",null,"Cookie",w.cookie());}
    HttpResponse<String> write(String method,String path,Web w,Map<String,?> values)throws Exception{return request(method,path,values==null?null:body(values),"Cookie",w.cookie(),"X-CSRF-Token",w.csrf(),"Origin","http://localhost");}
    HttpResponse<String> change(Web w,String old,String replacement)throws Exception{return write("PUT","/api/platform/auth/password",w,Map.of("currentPassword",old,"newPassword",replacement));}
    long version(){return owner.queryForObject("select security_version from pet_control.platform_account where id=?",Long.class,id);}
    void error(HttpResponse<String> r,int status,String code){assertEquals(status,r.statusCode());assertEquals(code,json.readTree(r.body()).path("error").path("code").asText());assertFalse(r.body().contains(password));}
    @AfterEach void observe(TestInfo info)throws Exception{
        CONTROL.clear();var snapshot=Map.of("account",owner.queryForList("select id,login_name,status,security_version,authorization_version,version from pet_control.platform_account"),"event",owner.queryForList("select principal_type,actor_id,target_id,operation,result,occurred_at,trace_id from pet_control.platform_security_event"),"cleanup",owner.queryForList("select account_id,revoke_before,completed from pet_control.platform_session_cleanup"));
        var dir=Path.of("target/p05-04-observations");Files.createDirectories(dir);Files.writeString(dir.resolve(info.getTestMethod().orElseThrow().getName()+".json"),json.writeValueAsString(snapshot));
        assertTrue(TenantContextHolder.current().isEmpty());for(String k:List.of("tenantId","operatorId","storeId","traceId"))assertNull(org.slf4j.MDC.get(k));
    }
    @Test void initializerCreatesOnlyIndependentCanonicalAccountAndExplicitPermissions(){assertEquals("root",owner.queryForObject("select login_name from pet_control.platform_account",String.class));assertEquals(PlatformPermissions.DECLARED,Set.copyOf(owner.queryForList("select permission_code from pet_control.platform_permission",String.class)));assertEquals(1,owner.queryForObject("select count(*) from pet_control.platform_bootstrap",Integer.class));assertTrue(passwords.matches(password.toCharArray(),owner.queryForObject("select password_hash from pet_control.platform_account",String.class)));}
    @Test void repeatedBootstrapNeverResetsOrAddsAnotherAccount(){assertEquals(2,command("other",next,environment()));assertEquals(1,owner.queryForObject("select count(*) from pet_control.platform_account",Integer.class));assertTrue(passwords.matches(password.toCharArray(),owner.queryForObject("select password_hash from pet_control.platform_account",String.class)));}
    @Test void concurrentBootstrapHasOneCompleteWinner()throws Exception{owner.execute("truncate pet_control.platform_security_event,pet_control.platform_session_cleanup,pet_control.platform_bootstrap,pet_control.platform_permission,pet_control.platform_account");var barrier=new CyclicBarrier(2);try(var pool=Executors.newFixedThreadPool(2)){var a=pool.submit(() -> {barrier.await();return command("first",password,environment());});var b=pool.submit(() -> {barrier.await();return command("second",password,environment());});assertEquals(List.of(0,2),java.util.stream.Stream.of(a.get(),b.get()).sorted().toList());}assertEquals(1,owner.queryForObject("select count(*) from pet_control.platform_account",Integer.class));assertEquals(3,owner.queryForObject("select count(*) from pet_control.platform_permission",Integer.class));assertEquals(1,owner.queryForObject("select count(*) from pet_control.platform_bootstrap",Integer.class));}
    @Test void bootstrapFailureRollsBackAccountPermissionsAndMarker(){owner.execute("truncate pet_control.platform_security_event,pet_control.platform_session_cleanup,pet_control.platform_bootstrap,pet_control.platform_permission,pet_control.platform_account");owner.execute("revoke insert on pet_control.platform_bootstrap from pet_platform_bootstrap_owner");try{assertEquals(2,command("rollback",password,environment()));assertEquals(0,owner.queryForObject("select count(*) from pet_control.platform_account",Integer.class));assertEquals(0,owner.queryForObject("select count(*) from pet_control.platform_permission",Integer.class));assertEquals(0,owner.queryForObject("select count(*) from pet_control.platform_bootstrap",Integer.class));}finally{owner.execute("grant insert on pet_control.platform_bootstrap to pet_platform_bootstrap_owner");}}
    @Test void tenantBootstrapIdentityCannotInitializePlatform(){var env=new HashMap<>(environment());env.put("PET_PLATFORM_BOOTSTRAP_DATABASE_USERNAME",IdentityDatabaseSupport.BOOTSTRAP);assertEquals(2,command("blocked",password,env));}
    @Test void initializerRejectsParameterPasswordAndMalformedInput(){var out=new ByteArrayOutputStream();assertEquals(2,PlatformBootstrapCommand.run(new String[]{"--password",password},environment(),InputStream.nullInputStream(),new PrintStream(out),new PrintStream(out)));assertFalse(out.toString().contains(password));}
    @Test void correctWebLoginReturnsPlatformIdentityWithoutTenantOrToken()throws Exception{var w=web();var r=me(w);assertEquals(200,r.statusCode());assertEquals("PLATFORM",data(r).path("principalType").asText());assertTrue(data(r).path("tenantId").isNull());assertTrue(data(r).path("dataScope").isNull());assertEquals(0,data(r).path("authorizedStoreIds").size());assertEquals(id.toString(),data(r).path("principalId").asText());assertFalse(r.body().contains(w.cookie().split("=",2)[1]));}
    @Test void wrongMissingAndDisabledCredentialsHaveSamePublicFailure()throws Exception{for(String name:List.of("missing","root"))error(login(name,next),401,"LOGIN_FAILED");owner.update("update pet_control.platform_account set status='DISABLED' where id=?",id);error(login("root",password),401,"LOGIN_FAILED");}
    @Test void cookiesCsrfRotationAndSessionFixationDefenseAreReal()throws Exception{var pre=request("GET","/api/platform/auth/csrf",null);String old=data(pre).path("csrfToken").asText();var r=request("POST","/api/platform/auth/login",body(Map.of("loginName","root","password",password)),"Cookie",cookie(pre,"pet_dev_platform_pre"),"X-CSRF-Token",old,"Origin","http://localhost");assertEquals(200,r.statusCode());String raw=r.headers().allValues("Set-Cookie").stream().filter(s -> s.startsWith("pet_dev_platform_sid=")).findFirst().orElseThrow();assertTrue(raw.contains("Path=/api/platform/"));assertTrue(raw.contains("HttpOnly"));assertTrue(raw.contains("SameSite=Lax"));assertFalse(raw.contains("Domain="));String sid=cookie(r,"pet_dev_platform_sid");String csrf=data(request("GET","/api/platform/auth/csrf",null,"Cookie",sid)).path("csrfToken").asText();assertNotEquals(old,csrf);assertEquals(csrf,data(request("GET","/api/platform/auth/csrf",null,"Cookie",sid)).path("csrfToken").asText());error(write("POST","/api/platform/auth/logout",new Web(sid,old),null),403,"CSRF_INVALID");}
    @Test void csrfOriginAndBodyUnknownFieldsFailClosed()throws Exception{for(String path:List.of("/api/%70latform/auth/login","/%61pi/platform/auth/login","/api/platform/auth/log%69n","/api/platform;alias/auth/login"))error(request("POST",path,body(Map.of("loginName","root","password",password))),400,"BAD_REQUEST");for(String path:List.of("/api/%61dmin/auth/login","/%61pi/admin/auth/login","/api/admin;alias/auth/login"))error(request("POST",path,body(Map.of("tenantCode",tenant,"loginName","admin","password",staffPassword))),400,"BAD_REQUEST");var w=web();error(request("POST","/api/platform/auth/logout",null,"Cookie",w.cookie()),403,"CSRF_INVALID");error(request("POST","/api/platform/auth/logout",null,"Cookie",w.cookie(),"X-CSRF-Token",w.csrf(),"Origin","https://other.invalid"),403,"CSRF_INVALID");error(write("PUT","/api/platform/auth/password",w,Map.of("currentPassword",password,"newPassword",next,"tenantId",staff.tenantId())),400,"BAD_REQUEST");assertEquals(0,version());}
    @Test void staffTokenAndCookieCannotAccessPlatform()throws Exception{String t=staffToken("admin");error(request("GET","/api/platform/auth/me",null,"X-Staff-Token","Bearer "+t),401,"AUTH_DOMAIN_MISMATCH");error(me(staffWeb()),401,"AUTH_REQUIRED");error(me(new Web("pet_dev_platform_sid="+t,"")),401,"SESSION_EXPIRED");}
    @Test void platformCookieAndClientTenantCannotEnterTenantPersistence()throws Exception{var w=web();error(request("GET","/api/admin/auth/me",null,"Cookie",w.cookie()),401,"AUTH_REQUIRED");error(request("GET","/api/admin/__platform-test/business?tenantId="+staff.tenantId(),null,"Cookie",w.cookie()),401,"AUTH_REQUIRED");error(request("GET","/api/platform/__platform-test/tenant?tenantId="+staff.tenantId(),null,"Cookie",w.cookie()),404,"RESOURCE_NOT_FOUND");assertTrue(data(request("GET","/api/platform/__platform-test/context",null,"Cookie",w.cookie())).path("tenantAbsent").asBoolean());}
    @Test void twoValidDomainCookiesRouteIndependentlyInEitherOrder()throws Exception{var p=web();var s=staffWeb();for(String both:List.of(p.cookie()+"; "+s.cookie(),s.cookie()+"; "+p.cookie())){assertEquals(id.toString(),data(request("GET","/api/platform/auth/me",null,"Cookie",both)).path("principalId").asText());assertEquals(staff.employeeId().toString(),data(request("GET","/api/admin/auth/me",null,"Cookie",both)).path("principalId").asText());}}
    @Test void twoCsrfDomainsCannotBeInterchanged()throws Exception{var p=web();var s=staffWeb();String both=p.cookie()+"; "+s.cookie();error(write("POST","/api/platform/auth/logout",new Web(both,s.csrf()),null),403,"CSRF_INVALID");error(write("POST","/api/admin/auth/logout",new Web(both,p.csrf()),null),403,"CSRF_INVALID");assertEquals(200,me(p).statusCode());}
    @Test void duplicatePlatformCookieAndHeaderSelectionAreRejected()throws Exception{var p=web();error(me(new Web(p.cookie()+"; "+p.cookie(),p.csrf())),400,"AUTH_CREDENTIAL_AMBIGUOUS");error(request("GET","/api/platform/auth/me",null,"Cookie",p.cookie(),"X-Platform-Token","Bearer "+p.cookie().split("=",2)[1]),400,"AUTH_CREDENTIAL_AMBIGUOUS");error(request("GET","/api/platform/auth/me",null,"X-Login-Type","platform"),401,"AUTH_DOMAIN_MISMATCH");}
    @Test void sameUuidInStaffAndPlatformHasIndependentPermissionsAndRevocation()throws Exception{owner.update("insert into identity_employee(id,tenant_id,login_name,display_name,status,password_hash) values(?,?,?,'同UUID技术员工','ACTIVE',?)",id,staff.tenantId(),"same-id",passwords.hash(staffPassword.toCharArray()));String t=staffToken("same-id");var p=web();assertEquals(200,write("POST","/api/platform/auth/logout-all",p,Map.of("currentPassword",password)).statusCode());assertEquals(200,request("GET","/api/admin/auth/me",null,"X-Staff-Token","Bearer "+t).statusCode());assertNotNull(redis.getSession("pet:test:staff:staff:session:"+id));assertNull(redis.getSession("pet:test:platform:platform:session:"+id));}
    @Test void currentLogoutInvalidatesOnlyCurrentPlatformSession()throws Exception{var one=web();var two=web();var staffSession=staffWeb();assertEquals(200,write("POST","/api/platform/auth/logout",one,null).statusCode());assertEquals(401,me(one).statusCode());assertEquals(200,me(two).statusCode());assertEquals(200,request("GET","/api/admin/auth/me",null,"Cookie",staffSession.cookie()).statusCode());}
    @Test void changePasswordRevokesEveryPlatformSessionButLeavesStaff()throws Exception{var one=web();var two=web();var s=staffWeb();var done=change(one,password,next);assertEquals(200,done.statusCode());assertEquals("COMPLETE",done.headers().firstValue("X-Session-Cleanup").orElseThrow());assertEquals(1,version());assertEquals(401,me(one).statusCode());assertEquals(401,me(two).statusCode());assertEquals(200,request("GET","/api/admin/auth/me",null,"Cookie",s.cookie()).statusCode());error(login("root",password),401,"LOGIN_FAILED");assertEquals(200,me(web(next)).statusCode());}
    @Test void oldPasswordConfirmationNewRulesAndSamePasswordAreRejected()throws Exception{var w=web();error(change(w,next,password),403,"SECURITY_CONFIRMATION_FAILED");error(change(w,password,password),422,"VALIDATION_FAILED");error(change(w,password,"short"),422,"VALIDATION_FAILED");assertEquals(0,version());assertEquals(200,me(w).statusCode());}
    @Test void permissionsAreRequiredRatherThanIsLogin()throws Exception{var w=web();owner.update("delete from pet_control.platform_permission where account_id=? and permission_code=?",id,PlatformPermissions.PASSWORD);error(change(w,password,next),403,"PERMISSION_DENIED");owner.update("delete from pet_control.platform_permission where account_id=? and permission_code=?",id,PlatformPermissions.SESSION);error(me(w),403,"PERMISSION_DENIED");}
    @Test void redisCleanupFailureKeepsOldSessionsLogicallyInvalidAndCompensates()throws Exception{var old=web();CONTROL.cleanupFailure=true;var r=change(old,password,next);assertEquals(200,r.statusCode());assertEquals("PENDING",r.headers().firstValue("X-Session-Cleanup").orElseThrow());error(me(old),401,"SESSION_REVOKED");CONTROL.cleanupFailure=false;var fresh=web(next);assertEquals(200,me(fresh).statusCode());assertEquals(0,owner.queryForObject("select count(*) from pet_control.platform_session_cleanup where not completed",Integer.class));}
    @Test void delayedCleanupDoesNotDeleteNewGeneration()throws Exception{var old=web();CONTROL.cleanup=new Gate();try(var pool=Executors.newSingleThreadExecutor()){var action=pool.submit(() -> change(old,password,next));assertTrue(CONTROL.cleanup.entered.await(10,TimeUnit.SECONDS));var fresh=web(next);CONTROL.cleanup.release.countDown();assertEquals(200,action.get().statusCode());assertEquals(200,me(fresh).statusCode());assertEquals(401,me(old).statusCode());}}
    @Test void loginWithPreviouslyVerifiedOldPasswordCannotIssueNewGeneration()throws Exception{var existing=web();CONTROL.login=new Gate();try(var pool=Executors.newSingleThreadExecutor()){var attempt=pool.submit(() -> login("root",password));assertTrue(CONTROL.login.entered.await(10,TimeUnit.SECONDS));assertEquals(200,change(existing,password,next).statusCode());CONTROL.login.release.countDown();error(attempt.get(),401,"LOGIN_FAILED");assertEquals(200,me(web(next)).statusCode());}}
    @Test void concurrentChangesCommitExactlyOnce()throws Exception{var a=web();var b=web();var gate=new CyclicBarrier(2);try(var pool=Executors.newFixedThreadPool(2)){var first=pool.submit(() -> {gate.await();return change(a,password,next);});var second=pool.submit(() -> {gate.await();return change(b,password,UUID.randomUUID()+"另一秘密");});assertEquals(List.of(200,401),java.util.stream.Stream.of(first.get().statusCode(),second.get().statusCode()).sorted().toList());}assertEquals(1,version());}
    @Test void securityRecordFailureRollsBackCredentialGenerationAndIntent()throws Exception{var w=web();CONTROL.eventFailure=true;error(change(w,password,next),503,"DEPENDENCY_UNAVAILABLE");CONTROL.eventFailure=false;assertEquals(0,version());assertEquals(0,owner.queryForObject("select count(*) from pet_control.platform_session_cleanup",Integer.class));assertTrue(passwords.matches(password.toCharArray(),owner.queryForObject("select password_hash from pet_control.platform_account",String.class)));assertEquals(200,me(w).statusCode());}
    @Test void realDatabaseFaultIs503RatherThanWrongPassword()throws Exception{owner.execute("revoke execute on function pet_control.authentication_candidate(text) from pet_runtime");try{error(login("root",password),503,"DEPENDENCY_UNAVAILABLE");}finally{owner.execute("grant execute on function pet_control.authentication_candidate(text) to pet_runtime");}}
    @Test void realRedisFaultFailsClosedAndRetainsCookie()throws Exception{var w=web();RedisTestSupport.REDIS.getDockerClient().pauseContainerCmd(RedisTestSupport.REDIS.getContainerId()).exec();try{var r=me(w);error(r,503,"DEPENDENCY_UNAVAILABLE");assertTrue(r.headers().allValues("Set-Cookie").isEmpty());}finally{RedisTestSupport.REDIS.getDockerClient().unpauseContainerCmd(RedisTestSupport.REDIS.getContainerId()).exec();}assertEquals(200,me(w).statusCode());}
    @Test void platformRedisEntryAcceptsOnlyRealAuthorizedPlatformAndAsyncRejects()throws Exception{var p=web();var s=staffWeb();assertEquals(200,request("GET","/api/platform/__platform-test/redis",null,"Cookie",p.cookie()).statusCode());assertEquals(403,request("GET","/api/admin/__platform-test/redis",null,"Cookie",s.cookie()).statusCode());assertEquals(404,request("GET","/api/platform/__platform-test/async",null,"Cookie",p.cookie()).statusCode());}
    @Test void loginRateLimitIsIndependentFromStaffAndHasRetryAfter()throws Exception{for(int i=0;i<10;i++)error(login("root",next),401,"LOGIN_FAILED");var r=login("root",next);error(r,429,"RATE_LIMITED");assertTrue(r.headers().firstValue("Retry-After").isPresent());assertEquals(200,request("GET","/api/admin/auth/me",null,"X-Staff-Token","Bearer "+staffToken("admin")).statusCode());}
    @Test void runtimeCannotReadHashBootstrapOrElevateDatabaseRole()throws Exception{try(var c=DriverManager.getConnection(POSTGRES.getJdbcUrl(),IdentityDatabaseSupport.RUNTIME,POSTGRES.getPassword());var s=c.createStatement()){for(String sql:List.of("select password_hash from pet_control.platform_account","select * from pet_control.platform_security_event","set role pet_platform_auth_owner","set role pet_platform_bootstrap","alter table identity_employee disable row level security"))assertThrows(SQLException.class,() -> s.execute(sql));try(var result=s.executeQuery("select rolsuper or rolbypassrls or rolcreaterole or rolcreatedb from pg_roles where rolname=current_user")){assertTrue(result.next());assertFalse(result.getBoolean(1));}try(var q=c.prepareStatement("select pet_control.bootstrap_platform(?,?,?,?)")){q.setObject(1,UUID.randomUUID());q.setString(2,"forbidden");q.setString(3,"拒绝");q.setString(4,passwords.hash(password.toCharArray()));assertThrows(SQLException.class,q::execute);}}}
    @Test void recordsHaveExplicitPlatformScopeAndNoSecrets()throws Exception{var w=web();error(change(w,next,password),403,"SECURITY_CONFIRMATION_FAILED");assertEquals(200,change(w,password,next).statusCode());for(var row:owner.queryForList("select * from pet_control.platform_security_event")){assertFalse(row.containsKey("tenant_id"));assertEquals("PLATFORM",row.get("principal_type"));assertNotNull(row.get("trace_id"));for(String secret:List.of(password,next,w.cookie().split("=",2)[1],w.csrf(),"$pbkdf2"))assertFalse(row.toString().contains(secret));}}
    @Test void requestExceptionsLeaveNoContextOrMdcOnReusedThread()throws Exception{var w=web();for(int i=0;i<3;i++){assertEquals(500,request("GET","/api/platform/__platform-test/failure",null,"Cookie",w.cookie()).statusCode());assertTrue(data(request("GET","/api/platform/__platform-test/context",null,"Cookie",w.cookie())).path("tenantAbsent").asBoolean());}}
    @Test void realRedisCleanupPauseLeavesCommittedPasswordAndOldGenerationInvalid()throws Exception{var w=web();CONTROL.pauseCleanup=true;try{var r=change(w,password,next);assertEquals(200,r.statusCode());assertEquals("PENDING",r.headers().firstValue("X-Session-Cleanup").orElseThrow());assertEquals(1,version());}finally{RedisTestSupport.REDIS.getDockerClient().unpauseContainerCmd(RedisTestSupport.REDIS.getContainerId()).exec();}error(me(w),401,"SESSION_REVOKED");assertEquals(200,me(web(next)).statusCode());}
    @Test void sensitiveAttemptsUseAtomicIndependentPlatformFrequencyControl()throws Exception{var w=web();var gate=new CountDownLatch(1);try(var pool=Executors.newFixedThreadPool(12)){var futures=new ArrayList<Future<Integer>>();for(int i=0;i<24;i++)futures.add(pool.submit(() -> {gate.await();return change(w,next,password).statusCode();}));gate.countDown();var codes=new ArrayList<Integer>();for(var f:futures)codes.add(f.get());assertEquals(8,codes.stream().filter(c -> c==403).count());assertEquals(16,codes.stream().filter(c -> c==429).count());}assertEquals(0,version());assertEquals(200,me(w).statusCode());}
    @Test void secureCookiePolicyIsSharedAndInsecureProductionIsRejected(){var env=new org.springframework.mock.env.MockEnvironment().withProperty("pet.environment","prod").withProperty("pet.public-origin","https://example.invalid");var security=new WebCookieSecurity("platform","/api/platform/",env);var response=new org.springframework.mock.web.MockHttpServletResponse();security.setCookie(response,security.cookieName(),"temporary-policy-value",false);String value=response.getHeader("Set-Cookie");assertTrue(value.startsWith("__Secure-pet_platform_sid="));for(String required:List.of("Secure","HttpOnly","SameSite=Lax","Path=/api/platform/"))assertTrue(value.contains(required));env.withProperty("pet.auth.cookie-secure","false");assertThrows(IllegalStateException.class,() -> new WebCookieSecurity("platform","/api/platform/",env));}
    @Test void reloginRotatesCurrentPlatformSessionAndPreservesStaff()throws Exception{var old=web();var staffSession=staffWeb();var r=write("POST","/api/platform/auth/login",old,Map.of("loginName","root","password",password));assertEquals(200,r.statusCode());String sid=cookie(r,"pet_dev_platform_sid");assertNotEquals(old.cookie(),sid);String csrf=data(request("GET","/api/platform/auth/csrf",null,"Cookie",sid)).path("csrfToken").asText();assertNotEquals(old.csrf(),csrf);assertEquals(401,me(old).statusCode());assertEquals(200,request("GET","/api/admin/auth/me",null,"Cookie",staffSession.cookie()).statusCode());}
    @TestConfiguration(proxyBeanMethods=false) static class Probes {
        @Bean TestEndpoints endpoints(CurrentPrincipalProvider provider,PlatformRedisAccess redis,TenantTaskExecutor tasks){return new TestEndpoints(provider,redis,tasks);}
        @Bean static BeanPostProcessor faultGates(){return new BeanPostProcessor(){@Override public Object postProcessAfterInitialization(Object bean,String name){
            Class<?> api=bean instanceof PlatformSessionPort?PlatformSessionPort.class:bean instanceof PlatformIdentityStore?PlatformIdentityStore.class:null;if(api==null)return bean;
            return java.lang.reflect.Proxy.newProxyInstance(api.getClassLoader(),new Class<?>[]{api},(proxy,method,args) -> {
                if(method.getName().equals("create") && CONTROL.login!=null)CONTROL.login.waitHere();
                if(method.getName().equals("revokeBefore")){if(CONTROL.pauseCleanup){CONTROL.pauseCleanup=false;RedisTestSupport.REDIS.getDockerClient().pauseContainerCmd(RedisTestSupport.REDIS.getContainerId()).exec();}if(CONTROL.cleanupFailure)throw new BusinessException(ErrorCode.DEPENDENCY_UNAVAILABLE);if(CONTROL.cleanup!=null)CONTROL.cleanup.waitHere();}
                if(method.getName().equals("event") && CONTROL.eventFailure && !"LOGIN".equals(args[1]))throw new BusinessException(ErrorCode.DEPENDENCY_UNAVAILABLE);
                try{return method.invoke(bean,args);}catch(InvocationTargetException e){throw e.getCause();}
            });
        }};}
    }
    @RestController static class TestEndpoints {
        final CurrentPrincipalProvider provider;final PlatformRedisAccess redis;final TenantTaskExecutor tasks;
        TestEndpoints(CurrentPrincipalProvider provider,PlatformRedisAccess redis,TenantTaskExecutor tasks){this.provider=provider;this.redis=redis;this.tasks=tasks;}
        @GetMapping("/api/platform/__platform-test/context") public com.pet.platform.shared.api.ApiResponse.Success<Map<String,Object>> context(){return com.pet.platform.shared.api.ApiResponse.success(Map.of("tenantAbsent",TenantContextHolder.current().isEmpty(),"type",provider.currentPrincipal().orElseThrow().principalType().name()));}
        @GetMapping("/api/platform/__platform-test/tenant") public Object tenant(){TenantScopeGuard.requireBusiness();return null;}
        @GetMapping("/api/platform/__platform-test/async") public Object async(){tasks.submit(() -> true);return null;}
        @GetMapping({"/api/platform/__platform-test/redis","/api/admin/__platform-test/redis"}) public com.pet.platform.shared.api.ApiResponse.Success<Boolean> redis(){var key=redis.resource("identity","probe");redis.write(key,"技术资源",java.time.Duration.ofSeconds(10));boolean found=redis.read(key).isPresent();redis.delete(key);return com.pet.platform.shared.api.ApiResponse.success(found);}
        @GetMapping("/api/platform/__platform-test/failure") public Object failure(){throw new IllegalStateException("测试请求故障");}
    }
}
