package com.pet.testing.authentication;

import com.pet.platform.Application;
import com.pet.platform.identity.application.*;
import com.pet.platform.identity.application.authentication.*;
import com.pet.platform.identity.application.bootstrap.*;
import com.pet.platform.identity.infrastructure.bootstrap.BootstrapJdbc;
import com.pet.platform.identity.infrastructure.session.*;
import com.pet.platform.shared.api.*;
import com.pet.platform.shared.exception.BusinessException;
import com.pet.platform.shared.tenancy.*;
import com.pet.testing.*;
import java.net.*;
import java.net.http.*;
import java.nio.file.*;
import java.lang.reflect.*;
import java.sql.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.config.BeanPostProcessor;
import org.springframework.boot.test.context.*;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.context.annotation.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.web.bind.annotation.*;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.json.JsonMapper;
import static org.junit.jupiter.api.Assertions.*;

/** 正式迁移、受限运行角色、真实密码登录；所有故障与屏障仅在测试Bean装饰器。 */
@SpringBootTest(classes=Application.class,webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT,properties="pet.async.threads=1")
@ActiveProfiles("test") @Import(StaffCredentialSecurityIT.Probes.class)
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class StaffCredentialSecurityIT extends PostgresIntegrationSupport {
    @LocalServerPort int port;
    @Autowired PasswordService passwords;
    @Autowired AuthenticationRedis redis;
    @Autowired StaffSessionPort sessions;
    @Autowired JsonMapper json;
    @Autowired TenantTaskExecutor tasks;
    @Autowired QueueProbe queue;
    JdbcTemplate owner;
    BootstrapResult initialized;
    String code,password,next,temporary;
    UUID target;
    final HttpClient client=HttpClient.newHttpClient();
    static final Controls CONTROL=new Controls();
    record Web(String cookie,String csrf) { }
    @BeforeAll void owner(){owner=new JdbcTemplate(new DriverManagerDataSource(POSTGRES.getJdbcUrl(),POSTGRES.getUsername(),POSTGRES.getPassword()));}
    @BeforeEach void initialize(){
        CONTROL.clear();password=UUID.randomUUID()+" 容器😀 ";next=UUID.randomUUID()+" 新秘密😀 ";temporary=UUID.randomUUID()+" 临时秘密😀 ";
        redis.stringRedisTemplate.delete(List.of("pet:test:auth:staff:ip:"+SaStaffSessions.digest("127.0.0.1"),"pet:test:auth:staff:sip:"+SaStaffSessions.digest("127.0.0.1")));
        code="s"+UUID.randomUUID().toString().replace("-","").substring(0,20);initialized=initializeTenant(code);
        // 本阶段无员工CRUD：次要员工使用正式表的技术初始化，全部身份仍由生产密码登录建立。
        target=employee("worker",false);
    }
    BootstrapResult initializeTenant(String tenant){try(var r=new BootstrapRequest(tenant,"安全技术租户","admin",password.toCharArray(),"store","安全技术门店")){
        return new IdentityBootstrap(new BootstrapJdbc(Map.of("PET_BOOTSTRAP_DATABASE_URL",POSTGRES.getJdbcUrl().split("\\?",2)[0],"PET_BOOTSTRAP_DATABASE_USERNAME",IdentityDatabaseSupport.BOOTSTRAP,"PET_BOOTSTRAP_DATABASE_PASSWORD",POSTGRES.getPassword())),passwords).initialize(r);
    }}
    UUID employee(String login,boolean admin){UUID id=UUID.randomUUID();owner.update("insert into identity_employee(id,tenant_id,login_name,display_name,status,password_hash) values(?,?,?,?,'ACTIVE',?)",id,initialized.tenantId(),login,"技术员工",passwords.hash(password.toCharArray()));
        owner.update("insert into identity_employee_store(id,tenant_id,employee_id,store_id) values(?,?,?,?)",UUID.randomUUID(),initialized.tenantId(),id,initialized.storeId());
        if(admin)owner.update("insert into identity_employee_role(id,tenant_id,employee_id,role_id) select ?,?,?,id from identity_role where tenant_id=? and code='tenant-admin'",UUID.randomUUID(),initialized.tenantId(),id,initialized.tenantId());return id;
    }
    void grantRevoke(){owner.update("insert into identity_role_permission(id,tenant_id,role_id,permission_code,scope_type) select ?,tenant_id,id,'identity:user:revoke-sessions','TENANT' from identity_role where tenant_id=? and code='tenant-admin'",UUID.randomUUID(),initialized.tenantId());}
    HttpResponse<String> request(String method,String path,String body,String...headers)throws Exception {
        var b=HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+path)).timeout(java.time.Duration.ofSeconds(20));for(int i=0;i<headers.length;i+=2)b.header(headers[i],headers[i+1]);if(body!=null)b.header("Content-Type","application/json");
        return client.send(b.method(method,body==null?HttpRequest.BodyPublishers.noBody():HttpRequest.BodyPublishers.ofString(body)).build(),HttpResponse.BodyHandlers.ofString());
    }
    String body(Map<String,?> values){return json.writeValueAsString(values);}
    JsonNode data(HttpResponse<String> r){return json.readTree(r.body()).path("data");}
    HttpResponse<String> login(String tenant,String name,String pwd)throws Exception{return request("POST","/api/admin/auth/token/login",body(Map.of("tenantCode",tenant,"loginName",name,"password",pwd)));}
    String token(String name)throws Exception{var r=login(code,name,password);assertEquals(200,r.statusCode());return data(r).path("token").path("value").asText();}
    String newToken(String name,String pwd)throws Exception{var r=login(code,name,pwd);assertEquals(200,r.statusCode());return data(r).path("token").path("value").asText();}
    HttpResponse<String> me(String t)throws Exception{return request("GET","/api/admin/auth/me",null,"X-Staff-Token","Bearer "+t);}
    HttpResponse<String> secured(String method,String path,Map<String,?> payload,String token)throws Exception{return request(method,path,body(payload),"X-Staff-Token","Bearer "+token);}
    String cookie(HttpResponse<String> r,String name){return r.headers().allValues("Set-Cookie").stream().filter(s -> s.startsWith(name+"=")).findFirst().orElseThrow().split(";",2)[0];}
    Web web(String name)throws Exception{var pre=request("GET","/api/admin/auth/csrf",null);var r=request("POST","/api/admin/auth/login",body(Map.of("tenantCode",code,"loginName",name,"password",password)),"Cookie",cookie(pre,"pet_dev_staff_pre"),"X-CSRF-Token",data(pre).path("csrfToken").asText(),"Origin","http://localhost");assertEquals(200,r.statusCode());String sid=cookie(r,"pet_dev_staff_sid");return new Web(sid,data(request("GET","/api/admin/auth/csrf",null,"Cookie",sid)).path("csrfToken").asText());}
    HttpResponse<String> change(String t,String old,String replacement)throws Exception{return secured("PUT","/api/admin/auth/password",Map.of("currentPassword",old,"newPassword",replacement),t);}
    HttpResponse<String> logoutAll(String t)throws Exception{return secured("POST","/api/admin/auth/logout-all",Map.of("currentPassword",password),t);}
    String resetPath(UUID id){return "/api/admin/identity/users/"+id+"/password";}
    String revokePath(UUID id){return "/api/admin/identity/users/"+id+"/revoke-sessions";}
    HttpResponse<String> reset(String t,UUID id,String pwd)throws Exception{return secured("PUT",resetPath(id),Map.of("version","0","currentPassword",password,"newPassword",pwd),t);}
    HttpResponse<String> revoke(String t,UUID id,String version)throws Exception{return secured("POST",revokePath(id),Map.of("version",version,"currentPassword",password),t);}
    void error(HttpResponse<String> r,int status,String code){assertEquals(status,r.statusCode());assertEquals(code,json.readTree(r.body()).path("error").path("code").asText());assertEquals("no-store",r.headers().firstValue("Cache-Control").orElseThrow());assertFalse(r.body().contains(password));assertFalse(r.body().contains(next));assertFalse(r.body().contains(temporary));}
    long security(UUID employee){return owner.queryForObject("select security_version from identity_employee where id=?",Long.class,employee);}
    void stored(UUID employee,String pwd,long version,boolean mustChange){assertTrue(passwords.matches(pwd.toCharArray(),owner.queryForObject("select password_hash from identity_employee where id=?",String.class,employee)));assertEquals(version,security(employee));assertEquals(mustChange,owner.queryForObject("select password_change_required from identity_employee where id=?",Boolean.class,employee));}
    long events(String result){return owner.queryForObject("select count(*) from identity_security_event where tenant_id=? and result=?",Long.class,initialized.tenantId(),result);}
    long pending(){return owner.queryForObject("select count(*) from identity_session_cleanup where tenant_id=? and not completed",Long.class,initialized.tenantId());}
    @AfterEach void observe(TestInfo info)throws Exception {
        CONTROL.clear();Map<String,Object> snapshot=new LinkedHashMap<>();snapshot.put("employees",owner.queryForList("select id,status,security_version,version,password_change_required from identity_employee where tenant_id=? order by id",initialized.tenantId()));snapshot.put("events",owner.queryForList("select operation,result,operator_id,target_employee_id,occurred_at,trace_id from identity_security_event where tenant_id=? order by occurred_at",initialized.tenantId()));snapshot.put("cleanup",owner.queryForList("select employee_id,revoke_before,completed from identity_session_cleanup where tenant_id=?",initialized.tenantId()));
        Path dir=Path.of("target/p05-03-observations");Files.createDirectories(dir);Files.writeString(dir.resolve(info.getTestMethod().orElseThrow().getName()+".json"),json.writeValueAsString(snapshot));
        assertTrue(TenantContextHolder.current().isEmpty());for(String k:List.of("tenantId","operatorId","storeId","traceId"))assertNull(org.slf4j.MDC.get(k));
    }
    @Test void correctPasswordChangesAndAllChannelsAndCsrfArePhysicallyRemoved()throws Exception {
        String one=token("admin"),two=token("admin");Web w=web("admin");String other=token("worker");var tenant=initializeTenant("t"+UUID.randomUUID().toString().substring(0,20));String otherTenant;
        // 另租户编码由数据库事实读取，避免依赖测试猜测。
        String tenantCode=owner.queryForObject("select code from platform_tenant where id=?",String.class,tenant.tenantId());otherTenant=data(login(tenantCode,"admin",password)).path("token").path("value").asText();
        var result=request("PUT","/api/admin/auth/password",body(Map.of("currentPassword",password,"newPassword",next)),"Cookie",w.cookie(),"Origin","http://localhost","X-CSRF-Token",w.csrf());assertEquals(200,result.statusCode());assertTrue(data(result).isNull());assertEquals("COMPLETE",result.headers().firstValue("X-Session-Cleanup").orElseThrow());assertTrue(result.headers().allValues("Set-Cookie").stream().filter(c -> c.contains("Max-Age=0")).count()==2);
        stored(initialized.employeeId(),next,1,false);assertEquals(1,events("SUCCESS"));assertEquals(0,pending());
        error(me(one),401,"SESSION_EXPIRED");error(me(two),401,"SESSION_EXPIRED");error(request("GET","/api/admin/auth/csrf",null,"Cookie",w.cookie()),401,"SESSION_EXPIRED");assertEquals(200,me(other).statusCode());assertEquals(200,me(otherTenant).statusCode());assertNull(redis.getSession("pet:test:staff:staff:session:"+initialized.employeeId()));assertNull(redis.getSession("pet:test:staff:staff:token-session:"+one));error(login(code,"admin",password),401,"LOGIN_FAILED");newToken("admin",next);
    }
    @Test void wrongConfirmationDoesNotChangeCredentialVersionOrSessionsAndHasIndependentFailureRecord()throws Exception{String t=token("admin");error(change(t,password+"wrong",next),403,"SECURITY_CONFIRMATION_FAILED");stored(initialized.employeeId(),password,0,false);assertEquals(0,pending());assertEquals(1,events("SECURITY_CONFIRMATION_FAILED"));assertEquals(200,me(t).statusCode());}
    @Test void invalidSameAndOversizedPasswordsAndUnknownFieldsAreRejectedWithoutSecrets()throws Exception{String t=token("admin");error(change(t,password,"short"),422,"VALIDATION_FAILED");error(change(t,password,password),422,"VALIDATION_FAILED");error(change(t,password,"界".repeat(129)),422,"VALIDATION_FAILED");error(change(t,password,"😀".repeat(129)),422,"VALIDATION_FAILED");error(secured("PUT","/api/admin/auth/password",Map.of("currentPassword",password,"newPassword",next,"employeeId",target),t),400,"BAD_REQUEST");stored(initialized.employeeId(),password,0,false);assertEquals(200,me(t).statusCode());}
    @Test void passwordsPreserveSpacesCaseUnicodeAndAreNotReadFromQuery()throws Exception{String t=token("admin");error(secured("PUT","/api/admin/auth/password?currentPassword=forbidden",Map.of("currentPassword",password,"newPassword",next),t),400,"BAD_REQUEST");assertEquals(200,change(t,password,next).statusCode());error(login(code,"admin",next.strip()),401,"LOGIN_FAILED");assertEquals(200,me(newToken("admin",next)).statusCode());}
    @Test void selfLogoutAllRequiresConfirmationAndReplaysWithOldSessionFail()throws Exception{String a=token("admin"),b=token("admin");error(secured("POST","/api/admin/auth/logout-all",Map.of("currentPassword",password+"wrong"),a),403,"SECURITY_CONFIRMATION_FAILED");assertEquals(200,logoutAll(a).statusCode());stored(initialized.employeeId(),password,1,false);error(me(b),401,"SESSION_EXPIRED");error(logoutAll(a),401,"SESSION_EXPIRED");assertEquals(200,me(token("admin")).statusCode());assertEquals(1,security(initialized.employeeId()));}
    @Test void missingWrongCsrfAndSourcesDoNotMutate()throws Exception{Web w=web("admin");String b=body(Map.of("currentPassword",password,"newPassword",next));error(request("PUT","/api/admin/auth/password",b,"Cookie",w.cookie(),"Origin","http://localhost"),403,"CSRF_INVALID");error(request("POST","/api/admin/auth/logout-all",body(Map.of("currentPassword",password)),"Cookie",w.cookie(),"Origin","http://localhost","X-CSRF-Token","x".repeat(43)),403,"CSRF_INVALID");error(request("PUT",resetPath(target),body(Map.of("version","0","currentPassword",password,"newPassword",temporary)),"Cookie",w.cookie(),"Origin","http://evil.invalid","X-CSRF-Token",w.csrf()),403,"CSRF_INVALID");stored(initialized.employeeId(),password,0,false);stored(target,password,0,false);assertEquals(0,events("SUCCESS"));}
    @Test void independentPermissionsAreRequiredAndOrdinaryStartupDoesNotGrantNewCode()throws Exception{String admin=token("admin"),worker=token("worker");error(reset(worker,target,temporary),403,"PERMISSION_DENIED");error(revoke(admin,target,"0"),403,"PERMISSION_DENIED");assertFalse(PermissionCatalog.ADMIN_PERMISSIONS.contains("identity:user:revoke-sessions"));assertTrue(PermissionCatalog.DECLARED.containsKey("identity:user:revoke-sessions"));assertEquals(9,data(me(admin)).path("permissionCodes").size());}
    @Test void adminResetForcesChangeAndInvalidatesAllTargetDevicesWithoutChangingActor()throws Exception{String admin=token("admin"),worker=token("worker");Web w=web("worker");assertEquals(200,reset(admin,target,temporary).statusCode());stored(target,temporary,1,true);error(me(worker),401,"SESSION_EXPIRED");error(request("GET","/api/admin/auth/me",null,"Cookie",w.cookie()),401,"SESSION_EXPIRED");assertEquals(200,me(admin).statusCode());error(login(code,"worker",password),401,"LOGIN_FAILED");String temp=newToken("worker",temporary);assertTrue(data(me(temp)).path("passwordChangeRequired").asBoolean());error(request("GET","/api/admin/missing-business",null,"X-Staff-Token","Bearer "+temp),403,"PASSWORD_CHANGE_REQUIRED");assertEquals(200,change(temp,temporary,next).statusCode());stored(target,next,2,false);error(me(temp),401,"SESSION_EXPIRED");assertFalse(data(me(newToken("worker",next))).path("passwordChangeRequired").asBoolean());}
    @Test void temporaryPasswordCannotUseManagementEvenIfPermissionsAreGrantedAndCanLogout()throws Exception{String admin=token("admin");assertEquals(200,reset(admin,target,temporary).statusCode());owner.update("insert into identity_employee_role(id,tenant_id,employee_id,role_id) select ?,?,?,id from identity_role where tenant_id=?",UUID.randomUUID(),initialized.tenantId(),target,initialized.tenantId());String t=newToken("worker",temporary);error(reset(t,initialized.employeeId(),next),403,"PASSWORD_CHANGE_REQUIRED");assertEquals(200,secured("POST","/api/admin/auth/logout-all",Map.of("currentPassword",temporary),t).statusCode());}
    @Test void crossTenantUnknownAndStoreOutsideTargetsAreHidden()throws Exception{String admin=token("admin");var other=initializeTenant("o"+UUID.randomUUID().toString().substring(0,20));error(reset(admin,other.employeeId(),temporary),404,"RESOURCE_NOT_FOUND");error(reset(admin,UUID.randomUUID(),temporary),404,"RESOURCE_NOT_FOUND");owner.update("update identity_role_permission set scope_type='STORES' where tenant_id=? and permission_code='identity:user:reset-password'",initialized.tenantId());UUID store=UUID.randomUUID();owner.update("insert into platform_store(id,tenant_id,code,name,status) values(?,?,'outside','范围外店','ACTIVE')",store,initialized.tenantId());owner.update("insert into identity_employee_store(id,tenant_id,employee_id,store_id) values(?,?,?,?)",UUID.randomUUID(),initialized.tenantId(),target,store);error(reset(admin,target,temporary),404,"RESOURCE_NOT_FOUND");stored(target,password,0,false);}
    @Test void storeManagerCanManageOnlyTargetsWhoseEntireStoreAndAuthorityAreCovered()throws Exception{String admin=token("admin");owner.update("update identity_role_permission set scope_type='STORES' where tenant_id=? and permission_code='identity:user:reset-password'",initialized.tenantId());assertEquals(200,reset(admin,target,temporary).statusCode());UUID protectedTarget=employee("powerful",false);UUID role=UUID.randomUUID();owner.update("insert into identity_role(id,tenant_id,code,name,status) values(?,?,'powerful','技术权限','ACTIVE')",role,initialized.tenantId());owner.update("insert into identity_employee_role(id,tenant_id,employee_id,role_id) values(?,?,?,?)",UUID.randomUUID(),initialized.tenantId(),protectedTarget,role);owner.update("insert into identity_role_permission(id,tenant_id,role_id,permission_code,scope_type) values(?,?,?,'identity:user:reset-password','TENANT')",UUID.randomUUID(),initialized.tenantId(),role);error(reset(admin,protectedTarget,next),403,"PERMISSION_DENIED");}
    @Test void selfTenantAdminSystemAccountsCannotBeResetButAdminSessionsCanBeRevoked()throws Exception{String admin=token("admin");UUID second=employee("second-admin",true);error(reset(admin,initialized.employeeId(),temporary),403,"PERMISSION_DENIED");error(reset(admin,second,temporary),403,"PERMISSION_DENIED");owner.update("update identity_employee set system_reserved=true where id=?",target);error(reset(admin,target,temporary),403,"PERMISSION_DENIED");grantRevoke();error(revoke(admin,target,"0"),403,"PERMISSION_DENIED");String other=token("second-admin");assertEquals(200,revoke(admin,second,"0").statusCode());error(me(other),401,"SESSION_EXPIRED");assertEquals(200,me(token("second-admin")).statusCode());}
    @Test void adminRevokeLeavesPasswordAndMustChangeFlagAndActorIntactAndOldVersionCannotRepeat()throws Exception{grantRevoke();String admin=token("admin"),a=token("worker");Web w=web("worker");assertEquals(200,revoke(admin,target,"0").statusCode());stored(target,password,1,false);error(me(a),401,"SESSION_EXPIRED");error(request("GET","/api/admin/auth/me",null,"Cookie",w.cookie()),401,"SESSION_EXPIRED");String fresh=token("worker");error(revoke(admin,target,"0"),409,"VERSION_CONFLICT");assertEquals(200,me(fresh).statusCode());assertEquals(200,me(admin).statusCode());assertEquals(1,events("SUCCESS"));}
    @Test void adminReconfirmationFailureHasNoChange()throws Exception{String t=token("admin");error(secured("PUT",resetPath(target),Map.of("version","0","currentPassword",password+"wrong","newPassword",temporary),t),403,"SECURITY_CONFIRMATION_FAILED");stored(target,password,0,false);assertEquals(1,events("SECURITY_CONFIRMATION_FAILED"));}
    @Test void databaseFailureAfterPasswordVersionAndIntentRollsEverythingBack()throws Exception{String t=token("admin");CONTROL.rollback.set(true);error(change(t,password,next),503,"DEPENDENCY_UNAVAILABLE");stored(initialized.employeeId(),password,0,false);assertEquals(0,pending());assertEquals(0,events("SUCCESS"));assertEquals(1,events("DEPENDENCY_UNAVAILABLE"));assertEquals(200,me(t).statusCode());}
    @Test void mandatoryAuditInsertFailureRollsBackCredentialAndIntent()throws Exception{String t=token("admin");owner.execute("REVOKE INSERT ON identity_security_event FROM pet_runtime");try{error(change(t,password,next),503,"DEPENDENCY_UNAVAILABLE");}finally{owner.execute("GRANT INSERT ON identity_security_event TO pet_runtime");}stored(initialized.employeeId(),password,0,false);assertEquals(0,pending());assertEquals(0,events("SUCCESS"));assertEquals(200,me(t).statusCode());}
    @Test void redisCleanupFailurePreservesLogicalRevocationAndLazyCompensationRemovesOnlyOldVersions()throws Exception{String a=token("admin"),b=token("admin");Web w=web("admin");CONTROL.cleanupFailures.set(2);var result=change(a,password,next);assertEquals(200,result.statusCode());assertEquals("PENDING",result.headers().firstValue("X-Session-Cleanup").orElseThrow());stored(initialized.employeeId(),next,1,false);assertEquals(1,pending());assertNotNull(redis.getSession("pet:test:staff:staff:token-session:"+b));error(me(b),401,"SESSION_REVOKED");error(request("GET","/api/admin/auth/me",null,"Cookie",w.cookie()),401,"SESSION_REVOKED");
        // 测试关闭create内部旧设备清理的前提不是生产开关：恢复后生产create自身会清旧设备。
        String fresh=newToken("admin",next);assertEquals(200,me(fresh).statusCode());assertEquals(1,pending());assertEquals(200,me(fresh).statusCode());assertEquals(0,pending());assertNotNull(redis.getSession("pet:test:staff:staff:token-session:"+fresh));assertEquals(1,events("SUCCESS"));}
    @Test void oldCleanupRunningAfterFreshLoginNeverDeletesFreshSession()throws Exception{grantRevoke();String admin=token("admin"),old=token("worker");CONTROL.cleanupFailures.set(1);assertEquals("PENDING",revoke(admin,target,"0").headers().firstValue("X-Session-Cleanup").orElseThrow());String fresh=token("worker");sessions.revokeBefore(initialized.tenantId(),target,1);assertEquals(200,me(fresh).statusCode());error(me(old),401,"SESSION_EXPIRED");assertNotNull(redis.getSession("pet:test:staff:staff:token-session:"+fresh));}
    @Test void concurrentPasswordChangesCannotBothOverwriteSuccessfully()throws Exception{String a=token("admin"),b=token("admin");CONTROL.parallel=new CyclicBarrier(2);try(var pool=Executors.newFixedThreadPool(2)){var x=pool.submit(() -> change(a,password,next));var y=pool.submit(() -> change(b,password,temporary));var r1=x.get(15,TimeUnit.SECONDS);var r2=y.get(15,TimeUnit.SECONDS);assertEquals(Set.of(200,401),Set.of(r1.statusCode(),r2.statusCode()));stored(initialized.employeeId(),r1.statusCode()==200?next:temporary,1,false);assertEquals(1,events("SUCCESS"));}}
    @Test void adminResetCompetesWithSelfChangeWithoutLosingEitherVersionRule()throws Exception{String admin=token("admin"),worker=token("worker");CONTROL.parallel=new CyclicBarrier(2);try(var pool=Executors.newFixedThreadPool(2)){var x=pool.submit(() -> reset(admin,target,temporary));var y=pool.submit(() -> change(worker,password,next));var a=x.get(15,TimeUnit.SECONDS);var b=y.get(15,TimeUnit.SECONDS);assertEquals(1,List.of(a,b).stream().filter(r -> r.statusCode()==200).count());assertTrue(a.statusCode()==200?b.statusCode()==401:a.statusCode()==409);stored(target,a.statusCode()==200?temporary:next,1,a.statusCode()==200);assertEquals(1,events("SUCCESS"));}}
    @Test void twoAdminsUsingSameResourceVersionHaveOneWinner()throws Exception{employee("second-admin",true);String a=token("admin"),b=token("second-admin");CONTROL.parallel=new CyclicBarrier(2);try(var pool=Executors.newFixedThreadPool(2)){var x=pool.submit(() -> reset(a,target,next));var y=pool.submit(() -> reset(b,target,temporary));var r1=x.get(15,TimeUnit.SECONDS);var r2=y.get(15,TimeUnit.SECONDS);assertEquals(Set.of(200,409),Set.of(r1.statusCode(),r2.statusCode()));stored(target,r1.statusCode()==200?next:temporary,1,true);assertEquals(1,events("SUCCESS"));}}
    @Test void loginCheckedOldPasswordCannotAcquireNewVersionDuringPasswordChange()throws Exception{String existing=token("admin");CONTROL.login=new Gate();try(var pool=Executors.newSingleThreadExecutor()){var attempt=pool.submit(() -> login(code,"admin",password));assertTrue(CONTROL.login.entered.await(10,TimeUnit.SECONDS));assertEquals(200,change(existing,password,next).statusCode());CONTROL.login.release.countDown();error(attempt.get(15,TimeUnit.SECONDS),401,"LOGIN_FAILED");assertEquals(200,me(newToken("admin",next)).statusCode());assertEquals(1,redis.getSession("pet:test:staff:staff:session:"+initialized.employeeId()).getTerminalList().size());}}
    @Test void loginCompetingWithLogoutAllRejectsOldGenerationAndFreshLoginRemains()throws Exception{String existing=token("admin");CONTROL.login=new Gate();try(var pool=Executors.newSingleThreadExecutor()){var attempt=pool.submit(() -> login(code,"admin",password));assertTrue(CONTROL.login.entered.await(10,TimeUnit.SECONDS));// 撤销由当前线程发起，登录线程停在受控屏障。
        var done=logoutAll(existing);assertEquals(200,done.statusCode());CONTROL.login.release.countDown();error(attempt.get(15,TimeUnit.SECONDS),401,"LOGIN_FAILED");assertEquals(200,me(token("admin")).statusCode());}}
    void queuedThen(Runnable change,boolean expectedRun)throws Exception{var entered=new CountDownLatch(1);var release=new CountDownLatch(1);var blocker=tasks.submitUnscoped(() -> {entered.countDown();release.await();return null;});assertTrue(entered.await(5,TimeUnit.SECONDS));String t=token("admin");queue.ran.set(false);assertEquals(200,request("GET","/api/admin/__credential-test/queue",null,"X-Staff-Token","Bearer "+t).statusCode());try{change.run();}finally{release.countDown();}blocker.get(5,TimeUnit.SECONDS);if(expectedRun)queue.future.get(5,TimeUnit.SECONDS);else{var ex=assertThrows(ExecutionException.class,() -> queue.future.get(5,TimeUnit.SECONDS));assertInstanceOf(BusinessException.class,ex.getCause());}assertEquals(expectedRun,queue.ran.get());assertTrue(tasks.submitUnscoped(() -> TenantContextHolder.current().isEmpty() && org.slf4j.MDC.get("tenantId")==null && org.slf4j.MDC.get("traceId")==null).get(5,TimeUnit.SECONDS));}
    @Test void queuedTasksRecheckDatabaseGenerationAfterLogoutAll()throws Exception{String t=token("admin");queuedThen(() -> {try{assertEquals(200,logoutAll(t).statusCode());}catch(Exception e){throw new RuntimeException(e);}},false);}
    @Test void queuedTasksRecheckDatabaseGenerationAfterPasswordChange()throws Exception{String t=token("admin");queuedThen(() -> {try{assertEquals(200,change(t,password,next).statusCode());}catch(Exception e){throw new RuntimeException(e);}},false);}
    @Test void queuedTasksCannotExpandCapturedScopeAndCurrentRevokedPermissionRejects()throws Exception{owner.update("update identity_role_permission set scope_type='STORES' where tenant_id=? and permission_code='identity:user:list'",initialized.tenantId());queuedThen(() -> owner.update("update identity_role_permission set scope_type='TENANT' where tenant_id=? and permission_code='identity:user:list'",initialized.tenantId()),true);assertEquals(Set.of(DataScopeType.STORES),queue.scope.types());assertEquals(Set.of(initialized.storeId()),queue.scope.storeIds());queuedThen(() -> owner.update("delete from identity_role_permission where tenant_id=? and permission_code='identity:user:list'",initialized.tenantId()),false);}
    @Test void revokedCurrentDeviceAlsoRejectsQueuedTasksAndDatabaseFailureIsClosed()throws Exception{queuedThen(() -> {try{assertEquals(200,secured("POST","/api/admin/auth/logout",Map.of(),queue.token).statusCode());}catch(Exception e){throw new RuntimeException(e);}},false);}
    @Test void concurrentSensitiveLimitsAreAtomicAndFailuresDoNotLockEmployeePermanently()throws Exception{var gate=new CountDownLatch(1);try(var pool=Executors.newFixedThreadPool(16)){var results=new ArrayList<Future<Boolean>>();for(int i=0;i<24;i++)results.add(pool.submit(() -> {gate.await();try{sessions.limitSensitive("technical-source",initialized.tenantId(),initialized.employeeId(),target);return true;}catch(BusinessException e){assertEquals(ErrorCode.RATE_LIMITED,e.error().code());return false;}}));gate.countDown();int allowed=0;for(var r:results)if(r.get(10,TimeUnit.SECONDS))allowed++;assertEquals(8,allowed);}String t=token("admin");var r=change(t,password,next);error(r,429,"RATE_LIMITED");assertTrue(r.headers().firstValue("Retry-After").isPresent());stored(initialized.employeeId(),password,0,false);assertEquals(200,me(t).statusCode());}
    @Test void realRedisFrequencyFailureNeverSilentlyAllowsChange()throws Exception{String t=token("admin");RedisTestSupport.REDIS.getDockerClient().pauseContainerCmd(RedisTestSupport.REDIS.getContainerId()).exec();try{assertEquals(ErrorCode.DEPENDENCY_UNAVAILABLE,assertThrows(BusinessException.class,() -> sessions.limitSensitive("technical-source",initialized.tenantId(),initialized.employeeId(),target)).error().code());error(change(t,password,next),503,"DEPENDENCY_UNAVAILABLE");}finally{RedisTestSupport.REDIS.getDockerClient().unpauseContainerCmd(RedisTestSupport.REDIS.getContainerId()).exec();}stored(initialized.employeeId(),password,0,false);assertEquals(200,me(t).statusCode());}
    @Test void successfulAndFailedRecordsContainOnlyAllowlistedFieldsAndRlsRemainsForced()throws Exception{String t=token("admin");error(change(t,password+"wrong",next),403,"SECURITY_CONFIRMATION_FAILED");var done=change(t,password,next);assertEquals(200,done.statusCode());var rows=owner.queryForList("select * from identity_security_event where tenant_id=?",initialized.tenantId());assertEquals(2,rows.size());for(var row:rows){assertEquals(Set.of("id","tenant_id","operator_id","target_employee_id","operation","result","occurred_at","trace_id"),row.keySet());assertNotNull(row.get("trace_id"));String serialized=row.toString();for(String secret:List.of(password,next,t,"$pbkdf2"))assertFalse(serialized.contains(secret));}assertEquals(2,owner.queryForObject("select count(*) from pg_class where relname in ('identity_security_event','identity_session_cleanup') and relrowsecurity and relforcerowsecurity",Integer.class));}
    @Test void sensitiveWriteRechecksCurrentAuthorityBeforeCommit()throws Exception{String t=token("admin");CONTROL.beforeFinal=() -> owner.update("delete from identity_role_permission where tenant_id=? and permission_code='identity:user:reset-password'",initialized.tenantId());error(reset(t,target,temporary),403,"PERMISSION_DENIED");stored(target,password,0,false);assertEquals(0,pending());assertEquals(0,events("SUCCESS"));assertEquals(1,events("PERMISSION_DENIED"));}
    @Test void queuedAuthorityQueryFailureRefusesActionInsteadOfAssumingVersionIsUnchanged()throws Exception{try{queuedThen(() -> owner.execute("REVOKE EXECUTE ON FUNCTION pet_identity.staff_authorization(uuid,uuid) FROM pet_runtime"),false);}finally{owner.execute("GRANT EXECUTE ON FUNCTION pet_identity.staff_authorization(uuid,uuid) TO pet_runtime");}}
    @Test void databaseCommitSurvivesActualRedisOutageDuringPhysicalCleanup()throws Exception{String t=token("admin");CONTROL.afterCommit=() -> RedisTestSupport.REDIS.getDockerClient().pauseContainerCmd(RedisTestSupport.REDIS.getContainerId()).exec();try{var r=change(t,password,next);assertEquals(200,r.statusCode());assertEquals("PENDING",r.headers().firstValue("X-Session-Cleanup").orElseThrow());stored(initialized.employeeId(),next,1,false);assertEquals(1,pending());assertEquals(1,events("SUCCESS"));}finally{RedisTestSupport.REDIS.getDockerClient().unpauseContainerCmd(RedisTestSupport.REDIS.getContainerId()).exec();}error(me(t),401,"SESSION_REVOKED");String fresh=newToken("admin",next);assertEquals(200,me(fresh).statusCode());assertEquals(0,pending());}
    @Test void partiallyDeletedTokenIndexStillCleansOrphanSessionAndTerminal()throws Exception{grantRevoke();String a=token("admin"),old=token("worker");CONTROL.cleanupFailures.set(1);assertEquals("PENDING",revoke(a,target,"0").headers().firstValue("X-Session-Cleanup").orElseThrow());redis.delete("pet:test:staff:staff:token:"+old);assertNotNull(redis.getSession("pet:test:staff:staff:token-session:"+old));sessions.revokeBefore(initialized.tenantId(),target,1);assertNull(redis.getSession("pet:test:staff:staff:token-session:"+old));assertNull(redis.getSession("pet:test:staff:staff:session:"+target));assertNull(redis.get("pet:test:staff:staff:last-active:"+old));}
    static class Gate {final CountDownLatch entered=new CountDownLatch(1),release=new CountDownLatch(1);void await(){entered.countDown();try{if(!release.await(12,TimeUnit.SECONDS))throw new IllegalStateException("测试屏障超时");}catch(InterruptedException e){Thread.currentThread().interrupt();throw new IllegalStateException("测试屏障中断");}}}
    static class Controls {
        volatile Runnable afterCommit,beforeFinal;final ThreadLocal<Boolean> wroteSuccess=new ThreadLocal<>();AtomicBoolean rollback=new AtomicBoolean();AtomicInteger cleanupFailures=new AtomicInteger();volatile CyclicBarrier parallel;volatile Gate login;ThreadLocal<Integer> loginLoads=new ThreadLocal<>();
        void clear(){afterCommit=null;beforeFinal=null;wroteSuccess.remove();rollback.set(false);cleanupFailures.set(0);parallel=null;if(login!=null)login.release.countDown();login=null;loginLoads.remove();}
        Object invoke(Object bean,Method method,Object[] args)throws Throwable {
            if(method.getName().equals("lockTenant") && parallel!=null)parallel.await(10,TimeUnit.SECONDS);
            if(method.getName().equals("revokeBefore") && cleanupFailures.getAndUpdate(n -> Math.max(0,n-1))>0)throw new BusinessException(ErrorCode.DEPENDENCY_UNAVAILABLE);
            if(method.getName().equals("create"))loginLoads.set(0);
            try {
                Object value;try{value=method.invoke(bean,args);}catch(InvocationTargetException e){throw e.getCause();}
                if(method.getName().equals("load") && login!=null && loginLoads.get()!=null){int count=loginLoads.get()+1;loginLoads.set(count);if(count==1)login.await();}
                if(method.getName().equals("event") && "SUCCESS".equals(args[3])){wroteSuccess.set(true);if(beforeFinal!=null){beforeFinal.run();beforeFinal=null;}}
                if(method.getName().equals("transaction") && Boolean.TRUE.equals(wroteSuccess.get())){wroteSuccess.remove();if(afterCommit!=null){afterCommit.run();afterCommit=null;}}
                if(method.getName().equals("revoke") && rollback.compareAndSet(true,false))throw new BusinessException(ErrorCode.DEPENDENCY_UNAVAILABLE);
                return value;
            } finally {if(method.getName().equals("create"))loginLoads.remove();if(method.getName().equals("transaction"))wroteSuccess.remove();}
        }
    }
    @TestConfiguration(proxyBeanMethods=false) static class Probes {
        @Bean static BeanPostProcessor faultPorts(){return new BeanPostProcessor(){@Override public Object postProcessAfterInitialization(Object bean,String name){Class<?> type=switch(name){case "staffSecurityJdbc" -> StaffSecurityStore.class;case "staffSessionPort" -> StaffSessionPort.class;case "authenticationJdbc" -> IdentityLookup.class;default -> null;};return type==null?bean:java.lang.reflect.Proxy.newProxyInstance(type.getClassLoader(),new Class[]{type},(proxy,method,args) -> CONTROL.invoke(bean,method,args));}};}
        @Bean QueueProbe queueProbe(TenantTaskExecutor tasks){return new QueueProbe(tasks);}
    }
    @RestController static class QueueProbe {
        final TenantTaskExecutor tasks;volatile Future<?> future;volatile DataScope scope;volatile String token;final AtomicBoolean ran=new AtomicBoolean();QueueProbe(TenantTaskExecutor tasks){this.tasks=tasks;}
        @GetMapping("/api/admin/__credential-test/queue") ApiResponse.Success<Void> queue(jakarta.servlet.http.HttpServletRequest request){token=StaffHttpAuthentication.current(request).token();try(var s=TenantExecutionScope.forPermission("identity:user:list")){future=tasks.submit(() -> {scope=TenantContextHolder.current().orElseThrow().dataScope();ran.set(true);return null;});return ApiResponse.success(null);}}
    }
}
