package com.pet.testing.identity;
import com.pet.platform.Application;
import com.pet.platform.identity.application.PasswordService;
import com.pet.platform.identity.application.authentication.PlatformPermissions;
import com.pet.platform.identity.application.bootstrap.*;
import com.pet.platform.identity.infrastructure.bootstrap.*;
import com.pet.platform.customeridentity.application.*;
import com.pet.testing.*;
import java.net.*;
import java.net.http.*;
import java.sql.*;
import java.util.*;
import java.util.concurrent.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.test.context.ActiveProfiles;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.json.JsonMapper;
import static org.junit.jupiter.api.Assertions.*;
/** 正式PLATFORM Cookie/CSRF、真实PG/Redis；客户技术会话另标夹具，不冒充微信交换。 */
@SpringBootTest(classes=Application.class,webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT,properties={"pet.async.threads=1"})
@ActiveProfiles("test") @org.springframework.context.annotation.Import(ControlManagementIT.Probes.class) @TestInstance(TestInstance.Lifecycle.PER_CLASS)
class ControlManagementIT extends PostgresIntegrationSupport {
 @org.springframework.boot.test.context.TestConfiguration static class Probes {
  @org.springframework.context.annotation.Bean TaskProbe taskProbe(com.pet.platform.shared.tenancy.TenantTaskExecutor tasks){return new TaskProbe(tasks);}
 }
 @org.springframework.web.bind.annotation.RestController static class TaskProbe {
  final com.pet.platform.shared.tenancy.TenantTaskExecutor tasks;volatile Future<Boolean> future;final java.util.concurrent.atomic.AtomicBoolean ran=new java.util.concurrent.atomic.AtomicBoolean();
  TaskProbe(com.pet.platform.shared.tenancy.TenantTaskExecutor tasks){this.tasks=tasks;}
  @org.springframework.web.bind.annotation.GetMapping("/api/admin/__b02-task") com.pet.platform.shared.api.ApiResponse.Success<Boolean> queue(){try(var scope=com.pet.platform.shared.tenancy.TenantExecutionScope.forPermission("identity:user:list")){future=tasks.submit(()->{ran.set(true);return true;});return com.pet.platform.shared.api.ApiResponse.success(true);}}
 }
 @Autowired com.pet.platform.shared.tenancy.TenantTaskExecutor tasks;@Autowired TaskProbe taskProbe;
 @LocalServerPort int port;@Autowired PasswordService passwords;@Autowired JsonMapper json;
 @Autowired CustomerIdentityStore customers;@Autowired CustomerSessionPort customerSessions;
 @Autowired com.pet.platform.identity.infrastructure.session.AuthenticationRedis redis;
 final HttpClient client=HttpClient.newHttpClient();final String secret=UUID.randomUUID()+"隔离验收",next=UUID.randomUUID()+"更新验收";
 JdbcTemplate owner;Web root;UUID rootId;
 record Web(String cookie,String csrf){@Override public String toString(){return "Web[受限会话]";}}
 Map<String,String> platformEnv(){return Map.of("PET_PLATFORM_BOOTSTRAP_DATABASE_URL",POSTGRES.getJdbcUrl().split("\\?",2)[0],"PET_PLATFORM_BOOTSTRAP_DATABASE_USERNAME",IdentityDatabaseSupport.PLATFORM_BOOTSTRAP,"PET_PLATFORM_BOOTSTRAP_DATABASE_PASSWORD",POSTGRES.getPassword());}
 Map<String,String> staffEnv(){return Map.of("PET_BOOTSTRAP_DATABASE_URL",POSTGRES.getJdbcUrl().split("\\?",2)[0],"PET_BOOTSTRAP_DATABASE_USERNAME",IdentityDatabaseSupport.BOOTSTRAP,"PET_BOOTSTRAP_DATABASE_PASSWORD",POSTGRES.getPassword());}
 @BeforeAll void owner(){owner=new JdbcTemplate(new DriverManagerDataSource(POSTGRES.getJdbcUrl(),POSTGRES.getUsername(),POSTGRES.getPassword()));}
 @BeforeEach void initialize()throws Exception{
  owner.execute("truncate pet_control.management_event,pet_control.platform_security_event,pet_control.platform_session_cleanup,pet_control.platform_bootstrap,pet_control.platform_permission,pet_control.platform_account");
  var keys=redis.stringRedisTemplate.keys("pet:test:auth:*");if(keys!=null&&!keys.isEmpty())redis.stringRedisTemplate.delete(keys);
  rootId=new PlatformBootstrap(new PlatformBootstrapJdbc(platformEnv()),passwords).initialize("root","平台管理员",secret.toCharArray());
  assertEquals(19,new PlatformBootstrapJdbc(platformEnv()).upgradeManagement());assertEquals(0,new PlatformBootstrapJdbc(platformEnv()).upgradeManagement());root=login("root",secret);
 }
 HttpResponse<String> request(String method,String path,Object body,String... headers)throws Exception{
  var b=HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+path)).timeout(java.time.Duration.ofSeconds(20));for(int i=0;i<headers.length;i+=2)b.header(headers[i],headers[i+1]);if(body!=null)b.header("Content-Type","application/json");return client.send(b.method(method,body==null?HttpRequest.BodyPublishers.noBody():HttpRequest.BodyPublishers.ofString(json.writeValueAsString(body))).build(),HttpResponse.BodyHandlers.ofString());
 }
 HttpResponse<String> call(Web w,String method,String path,Object body)throws Exception{return request(method,"/api/platform"+path,body,"Cookie",w.cookie(),"X-CSRF-Token",w.csrf(),"Origin","http://localhost");}
 JsonNode data(HttpResponse<String> response){assertEquals(200,response.statusCode(),response.body());assertFalse(response.body().contains(secret));assertFalse(response.body().contains("$pbkdf2"));return json.readTree(response.body()).path("data");}
 void error(HttpResponse<String> response,int status,String code){assertEquals(status,response.statusCode(),response.body());assertEquals(code,json.readTree(response.body()).path("error").path("code").asText());}
 String cookie(HttpResponse<String> r,String name){return r.headers().allValues("Set-Cookie").stream().filter(s->s.startsWith(name+"=")).findFirst().orElseThrow().split(";",2)[0];}
 Web login(String name,String password)throws Exception{var pre=request("GET","/api/platform/auth/csrf",null);var login=request("POST","/api/platform/auth/login",Map.of("loginName",name,"password",password),"Cookie",cookie(pre,"pet_dev_platform_pre"),"X-CSRF-Token",data(pre).path("csrfToken").asText(),"Origin","http://localhost");data(login);String sid=cookie(login,"pet_dev_platform_sid");return new Web(sid,data(request("GET","/api/platform/auth/csrf",null,"Cookie",sid)).path("csrfToken").asText());}
 String unique(){return "t"+UUID.randomUUID().toString().replace("-","").substring(0,15);}
 UUID tenant(String code)throws Exception{return UUID.fromString(data(call(root,"POST","/tenants",Map.of("code",code,"name","正式验收租户"))).path("id").asText());}
 String tenantVersion(UUID id)throws Exception{return data(call(root,"GET","/tenants/"+id,null)).path("version").asText();}
 BootstrapResult complete(String code){try(var input=new BootstrapRequest(code,"正式验收租户","admin",secret.toCharArray(),null,null)){var result=new IdentityBootstrap(new BootstrapJdbc(staffEnv()),passwords).initialize(input);new BootstrapJdbc(staffEnv()).upgradeIdentityManagement(result.tenantId());return result;}}
 String staff(String code)throws Exception{return data(request("POST","/api/admin/auth/token/login",Map.of("tenantCode",code,"loginName","admin","password",secret))).path("token").path("value").asText();}
 List<String> basic(){return List.of(PlatformPermissions.SESSION,PlatformPermissions.PASSWORD,"platform:tenant:list","platform:tenant:detail","platform:account:list","platform:account:detail");}
 UUID account(String name,List<String> grants)throws Exception{return UUID.fromString(data(call(root,"POST","/accounts",Map.of("loginName",name,"displayName","平台验收账号","initialPassword",secret,"permissions",grants))).path("id").asText());}
 String accountVersion(UUID id)throws Exception{return data(call(root,"GET","/accounts/"+id,null)).path("version").asText();}
 void status(UUID id,String status)throws Exception{data(call(root,"PUT","/tenants/"+id+"/status",Map.of("version",tenantVersion(id),"status",status)));}
 @Test void tenantCreationInitializationAndLifecycleNeverRevivesOldStaffOrCustomer()throws Exception{
  String code=unique();UUID id=tenant(code);assertFalse(data(call(root,"GET","/tenants/"+id,null)).path("initialized").asBoolean());assertTrue(customers.tenant(code).isEmpty());
  var result=complete(code);assertEquals(id,result.tenantId());assertNull(result.storeId());assertTrue(data(call(root,"GET","/tenants/"+id,null)).path("initialized").asBoolean());
  String old=staff(code);assertEquals(200,request("GET","/api/admin/identity/users",null,"X-Staff-Token","Bearer "+old).statusCode());
  var customer=customers.register(id,"wx1234567890abcdef","b02_technical_customer").orElseThrow();String token=customerSessions.create(customer).token();assertEquals(200,request("GET","/api/customer/auth/me",null,"X-Customer-Token","Bearer "+token).statusCode());
  status(id,"DISABLED");assertEquals(401,request("GET","/api/admin/auth/me",null,"X-Staff-Token","Bearer "+old).statusCode());assertEquals(401,request("GET","/api/customer/auth/me",null,"X-Customer-Token","Bearer "+token).statusCode());assertTrue(customers.tenant(code).isEmpty());
  error(request("POST","/api/admin/auth/token/login",Map.of("tenantCode",code,"loginName","admin","password",secret)),401,"LOGIN_FAILED");status(id,"ACTIVE");assertEquals(401,request("GET","/api/admin/auth/me",null,"X-Staff-Token","Bearer "+old).statusCode());assertEquals(401,request("GET","/api/customer/auth/me",null,"X-Customer-Token","Bearer "+token).statusCode());assertNotEquals(old,staff(code));
 }
 @Test void tenantIsolationAndPlatformSessionSurviveForeignDisable()throws Exception{String a=unique(),b=unique();UUID id=tenant(a);tenant(b);complete(a);complete(b);String token=staff(b);status(id,"DISABLED");assertEquals(200,request("GET","/api/admin/auth/me",null,"X-Staff-Token","Bearer "+token).statusCode());data(call(root,"GET","/auth/me",null));}
 @Test void initializationFailureRollsBackAndRetryCreatesExactlyOneIdentity()throws Exception{String code=unique();UUID id=tenant(code);owner.execute("revoke insert on identity_employee_role from pet_bootstrap_owner");try{assertThrows(IllegalStateException.class,()->complete(code));assertEquals(0,owner.queryForObject("select count(*) from identity_employee where tenant_id=?",Integer.class,id));assertFalse(owner.queryForObject("select initialized from platform_tenant where id=?",Boolean.class,id));}finally{owner.execute("grant insert on identity_employee_role to pet_bootstrap_owner");}complete(code);assertThrows(IllegalStateException.class,()->complete(code));assertEquals(1,owner.queryForObject("select count(*) from identity_employee where tenant_id=?",Integer.class,id));}
 @Test void duplicateIdentifiersAndUnknownFieldsReturn422And400()throws Exception{String code=unique();tenant(code);error(call(root,"POST","/tenants",Map.of("code",code,"name","重复")),422,"VALIDATION_FAILED");account("reader",basic());error(call(root,"POST","/accounts",Map.of("loginName","reader","displayName","重复","initialPassword",secret,"permissions",basic())),422,"VALIDATION_FAILED");error(call(root,"POST","/tenants",Map.of("code",unique(),"name","越界","tenantId",UUID.randomUUID())),400,"BAD_REQUEST");}
 @Test void filtersPaginationSortingAndMalformedParametersAreReal()throws Exception{String code=unique();UUID id=tenant(code);var page=data(call(root,"GET","/tenants?keyword="+code+"&page=1&pageSize=1&sortBy=code&sortOrder=asc",null));assertEquals("1",page.path("total").asText());assertEquals(id.toString(),page.path("items").get(0).path("id").asText());error(call(root,"GET","/tenants?sortBy=passwordHash",null),400,"SORT_INVALID");error(call(root,"GET","/accounts?pageSize=101",null),400,"PAGINATION_INVALID");error(call(root,"GET","/tenants?status=DELETED",null),400,"BAD_REQUEST");error(call(root,"GET","/accounts?tenantId="+id,null),400,"BAD_REQUEST");}
 @Test void concurrentTenantEditsHaveOneWinner()throws Exception{UUID id=tenant(unique());var barrier=new CyclicBarrier(2);try(var pool=Executors.newFixedThreadPool(2)){var a=pool.submit(()->{barrier.await();return call(root,"PUT","/tenants/"+id,Map.of("version","0","name","并发甲"));});var b=pool.submit(()->{barrier.await();return call(root,"PUT","/tenants/"+id,Map.of("version","0","name","并发乙"));});assertEquals(List.of(200,409),java.util.stream.Stream.of(a.get().statusCode(),b.get().statusCode()).sorted().toList());}}
 @Test void readOnlyPlatformCannotWriteOrGrantOutsideAuthority()throws Exception{UUID id=account("reader",basic());Web reader=login("reader",secret);data(call(reader,"GET","/tenants",null));error(call(reader,"POST","/tenants",Map.of("code",unique(),"name","禁止")),403,"PERMISSION_DENIED");error(call(reader,"PUT","/accounts/"+id+"/permissions",Map.of("version","0","permissions",List.of(PlatformPermissions.SESSION,PlatformPermissions.PASSWORD,"platform:account:grant"))),403,"PERMISSION_DENIED");}
 @Test void grantOperatorCannotGivePermissionTheyDoNotHold()throws Exception{var grants=new ArrayList<>(basic());grants.addAll(List.of("platform:account:create","platform:account:grant"));account("delegator",grants);Web delegator=login("delegator",secret);var excess=new ArrayList<>(basic());excess.add("platform:tenant:disable");error(call(delegator,"POST","/accounts",Map.of("loginName","excess","displayName","过量授权","initialPassword",secret,"permissions",excess)),403,"PERMISSION_DENIED");assertEquals(0,owner.queryForObject("select count(*) from pet_control.platform_account where login_name='excess'",Integer.class));}
 @Test void accountGrantsStatusResetAndRevokeInvalidateOldSessions()throws Exception{UUID id=account("managed",basic());Web first=login("managed",secret);var reduced=List.of(PlatformPermissions.SESSION,PlatformPermissions.PASSWORD,"platform:tenant:list");data(call(root,"PUT","/accounts/"+id+"/permissions",Map.of("version",accountVersion(id),"permissions",reduced)));assertEquals(401,call(first,"GET","/auth/me",null).statusCode());Web second=login("managed",secret);error(call(second,"GET","/accounts",null),403,"PERMISSION_DENIED");data(call(root,"POST","/accounts/"+id+"/sessions/revoke",Map.of("version",accountVersion(id))));assertEquals(401,call(second,"GET","/auth/me",null).statusCode());Web third=login("managed",secret);data(call(root,"PUT","/accounts/"+id+"/password",Map.of("version",accountVersion(id),"newPassword",next)));assertEquals(401,call(third,"GET","/auth/me",null).statusCode());Web fourth=login("managed",next);data(call(root,"PUT","/accounts/"+id+"/status",Map.of("version",accountVersion(id),"status","DISABLED")));assertEquals(401,call(fourth,"GET","/auth/me",null).statusCode());data(call(root,"PUT","/accounts/"+id+"/status",Map.of("version",accountVersion(id),"status","ACTIVE")));assertEquals(401,call(fourth,"GET","/auth/me",null).statusCode());data(call(login("managed",next),"GET","/auth/me",null));}
 @Test void selfDisableAndSelfGrantChangesAreRejected()throws Exception{error(call(root,"PUT","/accounts/"+rootId+"/status",Map.of("version",accountVersion(rootId),"status","DISABLED")),403,"PERMISSION_DENIED");error(call(root,"PUT","/accounts/"+rootId+"/permissions",Map.of("version",accountVersion(rootId),"permissions",basic())),403,"PERMISSION_DENIED");}
 @Test void concurrentMutualDisableRetainsAnEffectiveManager()throws Exception{UUID other=account("manager",PlatformPermissions.DECLARED.stream().sorted().toList());Web manager=login("manager",secret);String v=accountVersion(rootId);var barrier=new CyclicBarrier(2);try(var pool=Executors.newFixedThreadPool(2)){var a=pool.submit(()->{barrier.await();return call(root,"PUT","/accounts/"+other+"/status",Map.of("version","0","status","DISABLED"));});var b=pool.submit(()->{barrier.await();return call(manager,"PUT","/accounts/"+rootId+"/status",Map.of("version",v,"status","DISABLED"));});var statuses=java.util.stream.Stream.of(a.get().statusCode(),b.get().statusCode()).sorted().toList();assertEquals(200,statuses.get(0));assertTrue(Set.of(401,409).contains(statuses.get(1)),statuses.toString());}assertEquals(1,owner.queryForObject("select count(*) from pet_control.platform_account where status='ACTIVE'",Integer.class));}
 @Test void lastManagerCannotBeRemovedByRestrictedDelegator()throws Exception{var grant=new ArrayList<>(basic());grant.add("platform:account:disable");account("operator",grant);Web operator=login("operator",secret);error(call(operator,"PUT","/accounts/"+rootId+"/status",Map.of("version",accountVersion(rootId),"status","DISABLED")),409,"BUSINESS_STATE_CONFLICT");}
 @Test void staffCustomerAndIdenticalUuidCannotEnterControlPlane()throws Exception{String code=unique();tenant(code);var t=complete(code);String staff=staff(code);error(request("GET","/api/platform/tenants",null,"X-Staff-Token","Bearer "+staff),401,"AUTH_DOMAIN_MISMATCH");error(request("GET","/api/platform/tenants",null,"X-Customer-Token","Bearer "+staff),401,"AUTH_DOMAIN_MISMATCH");error(request("GET","/api/admin/identity/organizations",null,"Cookie",root.cookie()),401,"AUTH_REQUIRED");owner.update("insert into identity_employee(id,tenant_id,login_name,display_name,status,password_hash) values(?,?,?,'同UUID员工','ACTIVE',?)",rootId,t.tenantId(),"same",passwords.hash(secret.toCharArray()));var response=request("POST","/api/admin/auth/token/login",Map.of("tenantCode",code,"loginName","same","password",secret));String token=data(response).path("token").path("value").asText();error(request("GET","/api/platform/accounts",null,"X-Staff-Token","Bearer "+token),401,"AUTH_DOMAIN_MISMATCH");data(call(root,"POST","/auth/logout",null));assertEquals(200,request("GET","/api/admin/auth/me",null,"X-Staff-Token","Bearer "+token).statusCode());}
 @Test void auditFailureRollsBackAllAccountRelationsVersionsAndCleanup()throws Exception{UUID id=account("rollback",basic());owner.execute("revoke insert on pet_control.management_event from pet_control_manager_owner");try{error(call(root,"PUT","/accounts/"+id+"/permissions",Map.of("version","0","permissions",List.of(PlatformPermissions.SESSION,PlatformPermissions.PASSWORD))),503,"DEPENDENCY_UNAVAILABLE");}finally{owner.execute("grant insert on pet_control.management_event to pet_control_manager_owner");}assertEquals("0",accountVersion(id));assertEquals(basic().size(),owner.queryForObject("select count(*) from pet_control.platform_permission where account_id=?",Integer.class,id));assertEquals(0,owner.queryForObject("select count(*) from pet_control.platform_session_cleanup where account_id=?",Integer.class,id));data(call(root,"PUT","/accounts/"+id,Map.of("version","0","displayName","恢复后")));}
 @Test void redisFailureFailsClosedAndRecoveryPreservesVersions()throws Exception{UUID id=tenant(unique());RedisTestSupport.REDIS.getDockerClient().pauseContainerCmd(RedisTestSupport.REDIS.getContainerId()).exec();try{error(call(root,"PUT","/tenants/"+id,Map.of("version","0","name","故障中")),503,"DEPENDENCY_UNAVAILABLE");}finally{RedisTestSupport.REDIS.getDockerClient().unpauseContainerCmd(RedisTestSupport.REDIS.getContainerId()).exec();}assertEquals("0",tenantVersion(id));data(call(root,"PUT","/tenants/"+id,Map.of("version","0","name","恢复后")));}
 @Test void databaseFailureFailsClosedAndRestoresRead()throws Exception{owner.execute("revoke execute on function pet_control.tenant_read(uuid,text,text,integer,integer,text,text) from pet_runtime");try{error(call(root,"GET","/tenants",null),503,"DEPENDENCY_UNAVAILABLE");}finally{owner.execute("grant execute on function pet_control.tenant_read(uuid,text,text,integer,integer,text,text) to pet_runtime");}data(call(root,"GET","/tenants",null));}
 @Test void queuedTaskCannotResumeAfterTenantDisableAndReenable()throws Exception{
  String code=unique();UUID id=tenant(code);complete(code);String token=staff(code);
  var entered=new CountDownLatch(1);var release=new CountDownLatch(1);var blocker=tasks.submitUnscoped(()->{entered.countDown();release.await();return true;});assertTrue(entered.await(5,TimeUnit.SECONDS));taskProbe.ran.set(false);
  try{data(request("GET","/api/admin/__b02-task",null,"X-Staff-Token","Bearer "+token));status(id,"DISABLED");status(id,"ACTIVE");}finally{release.countDown();}
  blocker.get(5,TimeUnit.SECONDS);var failure=assertThrows(ExecutionException.class,()->taskProbe.future.get(5,TimeUnit.SECONDS));assertInstanceOf(com.pet.platform.shared.exception.BusinessException.class,failure.getCause());assertFalse(taskProbe.ran.get());
  assertTrue(tasks.submitUnscoped(()->com.pet.platform.shared.tenancy.TenantContextHolder.current().isEmpty()).get(5,TimeUnit.SECONDS));
 }
 @Test void unknownPartialInitializationIsRejectedWithoutRepair()throws Exception{String code=unique();UUID id=tenant(code);owner.update("insert into identity_role(id,tenant_id,code,name,status) values(?,?,?,'未知半成品','ACTIVE')",UUID.randomUUID(),id,"partial");assertThrows(IllegalStateException.class,()->complete(code));assertFalse(owner.queryForObject("select initialized from platform_tenant where id=?",Boolean.class,id));assertEquals(0,owner.queryForObject("select count(*) from identity_employee where tenant_id=?",Integer.class,id));}
 @Test void runtimeHasNoDirectControlTablesOwnersOrSqlBypass()throws Exception{try(var c=DriverManager.getConnection(POSTGRES.getJdbcUrl(),IdentityDatabaseSupport.RUNTIME,POSTGRES.getPassword());var s=c.createStatement()){assertThrows(SQLException.class,()->s.execute("select * from pet_control.platform_account"));assertThrows(SQLException.class,()->s.execute("set role pet_control_manager_owner"));assertThrows(SQLException.class,()->s.execute("select pet_control.upgrade_management()"));assertThrows(SQLException.class,()->s.execute("select pet_control.require_management('platform:tenant:list',false)"));}}
 @Test void storesAndOrganizationsRemainSeparateAndTenantBound()throws Exception{String code=unique(),foreign=unique();UUID id=tenant(code);tenant(foreign);var t=complete(code);complete(foreign);var store=data(call(root,"POST","/tenants/"+id+"/stores",Map.of("code","main","name","正式门店")));assertEquals(1,data(call(root,"GET","/tenants/"+id+"/stores",null)).size());new BootstrapJdbc(staffEnv()).upgradeOrganizations(id);String token=staff(code);var org=data(request("POST","/api/admin/identity/organizations",Map.of("code","ops","name","内部组织"),"X-Staff-Token","Bearer "+token));String orgId=org.path("id").asText();assertEquals("1",data(request("GET","/api/admin/identity/organizations",null,"X-Staff-Token","Bearer "+token)).path("total").asText());new BootstrapJdbc(staffEnv()).upgradeOrganizations(owner.queryForObject("select id from platform_tenant where code=?",UUID.class,foreign));String other=staff(foreign);error(request("GET","/api/admin/identity/organizations/"+orgId,null,"X-Staff-Token","Bearer "+other),404,"RESOURCE_NOT_FOUND");error(call(root,"PUT","/tenants/"+id+"/stores/"+orgId,Map.of("version","0","name","不可混同")),404,"RESOURCE_NOT_FOUND");data(request("PUT","/api/admin/identity/organizations/"+orgId+"/status",Map.of("version","0","status","DISABLED"),"X-Staff-Token","Bearer "+token));assertEquals(1,data(call(root,"GET","/tenants/"+id+"/stores",null)).size());}
}
