/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/technical/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["technicalMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BigInteger: string;
        CurrentIdentity: components["schemas"]["PLATFORMIdentity"] | components["schemas"]["STAFFIdentity"] | components["schemas"]["CUSTOMERIdentity"];
        CUSTOMERIdentity: {
            authorizationVersion: components["schemas"]["BigInteger"];
            authorizedStoreIds: components["schemas"]["ID"][];
            dataScope: components["schemas"]["DataScope"];
            displayName: string;
            expiresAt: components["schemas"]["UtcInstant"];
            idleTimeoutSeconds: number;
            permissionCodes: string[];
            principalId: components["schemas"]["ID"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            principalType: "CUSTOMER";
            sessionId: components["schemas"]["ID"];
            tenantId: components["schemas"]["ID"];
        };
        DataScope: {
            grants: {
                permissionCode: string;
                scopes: ({
                    /** @constant */
                    type: "TENANT";
                } | {
                    storeIds: components["schemas"]["ID"][];
                    /** @constant */
                    type: "STORES";
                } | {
                    /** @constant */
                    type: "SELF";
                })[];
            }[];
        };
        /** Format: uuid */
        ID: string;
        MeResponse: {
            data: components["schemas"]["CurrentIdentity"];
            /** @constant */
            success: true;
            traceId: string;
        };
        Money: string;
        PLATFORMIdentity: {
            authorizationVersion: components["schemas"]["BigInteger"];
            authorizedStoreIds: components["schemas"]["ID"][];
            dataScope: null;
            displayName: string;
            expiresAt: components["schemas"]["UtcInstant"];
            idleTimeoutSeconds: number;
            permissionCodes: string[];
            principalId: components["schemas"]["ID"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            principalType: "PLATFORM";
            sessionId: components["schemas"]["ID"];
            tenantId: null;
        };
        STAFFIdentity: {
            authorizationVersion: components["schemas"]["BigInteger"];
            authorizedStoreIds: components["schemas"]["ID"][];
            dataScope: components["schemas"]["DataScope"];
            displayName: string;
            expiresAt: components["schemas"]["UtcInstant"];
            idleTimeoutSeconds: number;
            permissionCodes: string[];
            principalId: components["schemas"]["ID"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            principalType: "STAFF";
            sessionId: components["schemas"]["ID"];
            tenantId: components["schemas"]["ID"];
        };
        TypeFixture: {
            amount: components["schemas"]["Money"];
            /** Format: date */
            date: string;
            id: components["schemas"]["ID"];
            items: components["schemas"]["ID"][];
            nullableName: string | null;
            occurredAt: components["schemas"]["UtcInstant"];
            optionalName?: string;
            /** @enum {string} */
            status: "TEMPORARY" | "BOUND";
            version: components["schemas"]["BigInteger"];
        };
        /** Format: date-time */
        UtcInstant: string;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    technicalMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 技术协议示例 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
}
